/**
 * The Artistic Arboretum: works of art, grouped by medium.
 *
 * "Most important" is not a fact, so this makes no claim to be a ranking. It
 * is the set a general reader would expect to find in a survey of each medium
 * — the works that other works are compared against — chosen so that each
 * group spans its medium's history rather than its last century. Literature
 * starts at Gilgamesh, architecture at Giza, photography at the first
 * photograph, games at Spacewar!.
 *
 * `year` is a string because "c. 1503", "8th century BCE" and "1882–" are all
 * honest answers that a number is not. `article` is the Wikipedia title the
 * corner card fetches; it disambiguates where the plain title would not.
 */
export type Artwork = { title: string; artist: string; year: string; article: string }

export type Medium = { id: string; name: string; color: string; works: readonly Artwork[] }

export const MEDIA: readonly Medium[] = [
  {
    id: 'painting',
    name: 'Painting',
    color: '#e79ad8',
    works: [
      { title: 'Along the River During the Qingming Festival', artist: 'Zhang Zeduan', year: '12th century', article: 'Along the River During the Qingming Festival' },
      { title: 'The Birth of Venus', artist: 'Sandro Botticelli', year: 'c. 1485', article: 'The Birth of Venus' },
      { title: 'The Last Supper', artist: 'Leonardo da Vinci', year: '1498', article: 'The Last Supper (Leonardo)' },
      { title: 'Mona Lisa', artist: 'Leonardo da Vinci', year: 'c. 1503', article: 'Mona Lisa' },
      { title: 'The School of Athens', artist: 'Raphael', year: '1511', article: 'The School of Athens' },
      { title: 'The Night Watch', artist: 'Rembrandt', year: '1642', article: 'The Night Watch' },
      { title: 'Las Meninas', artist: 'Diego Velázquez', year: '1656', article: 'Las Meninas' },
      { title: 'Girl with a Pearl Earring', artist: 'Johannes Vermeer', year: 'c. 1665', article: 'Girl with a Pearl Earring' },
      { title: 'The Great Wave off Kanagawa', artist: 'Hokusai', year: 'c. 1831', article: 'The Great Wave off Kanagawa' },
      { title: 'Impression, Sunrise', artist: 'Claude Monet', year: '1872', article: 'Impression, Sunrise' },
      { title: 'The Starry Night', artist: 'Vincent van Gogh', year: '1889', article: 'The Starry Night' },
      { title: 'The Scream', artist: 'Edvard Munch', year: '1893', article: 'The Scream' },
      { title: 'The Kiss', artist: 'Gustav Klimt', year: '1908', article: 'The Kiss (Klimt)' },
      { title: 'The Persistence of Memory', artist: 'Salvador Dalí', year: '1931', article: 'The Persistence of Memory' },
      { title: 'Guernica', artist: 'Pablo Picasso', year: '1937', article: 'Guernica (Picasso)' },
      { title: 'Nighthawks', artist: 'Edward Hopper', year: '1942', article: 'Nighthawks (painting)' },
    ],
  },
  {
    id: 'sculpture',
    name: 'Sculpture',
    color: '#dcd6cb',
    works: [
      { title: 'Great Sphinx of Giza', artist: 'Unknown, Old Kingdom', year: 'c. 2500 BCE', article: 'Great Sphinx of Giza' },
      { title: 'Bust of Nefertiti', artist: 'Thutmose', year: 'c. 1345 BCE', article: 'Nefertiti Bust' },
      { title: 'Terracotta Army', artist: 'Qin dynasty artisans', year: 'c. 210 BCE', article: 'Terracotta Army' },
      { title: 'Winged Victory of Samothrace', artist: 'Unknown', year: 'c. 190 BCE', article: 'Winged Victory of Samothrace' },
      { title: 'Venus de Milo', artist: 'Alexandros of Antioch', year: 'c. 130 BCE', article: 'Venus de Milo' },
      { title: 'Laocoön and His Sons', artist: 'Agesander, Athenodoros and Polydorus', year: 'c. 40 BCE', article: 'Laocoön and His Sons' },
      { title: 'Moai', artist: 'The Rapa Nui people', year: 'c. 1250–1500', article: 'Moai' },
      { title: 'Great Buddha of Kamakura', artist: 'Ōno Gorōemon (attributed)', year: '1252', article: 'Kōtoku-in' },
      { title: 'Benin Bronzes', artist: 'Edo guild casters', year: '13th–16th century', article: 'Benin Bronzes' },
      { title: 'Pietà', artist: 'Michelangelo', year: '1499', article: 'Pietà (Michelangelo)' },
      { title: 'David', artist: 'Michelangelo', year: '1504', article: 'David (Michelangelo)' },
      { title: 'Statue of Liberty', artist: 'Frédéric Auguste Bartholdi', year: '1886', article: 'Statue of Liberty' },
      { title: 'The Thinker', artist: 'Auguste Rodin', year: '1904', article: 'The Thinker' },
      { title: 'Bird in Space', artist: 'Constantin Brâncuși', year: '1923', article: 'Bird in Space' },
      { title: 'Cloud Gate', artist: 'Anish Kapoor', year: '2006', article: 'Cloud Gate' },
    ],
  },
  {
    id: 'architecture',
    name: 'Architecture',
    color: '#c8b48a',
    works: [
      { title: 'Great Pyramid of Giza', artist: 'Hemiunu (attributed)', year: 'c. 2560 BCE', article: 'Great Pyramid of Giza' },
      { title: 'Parthenon', artist: 'Iktinos and Kallikrates', year: '432 BCE', article: 'Parthenon' },
      { title: 'Colosseum', artist: 'Vespasian and Titus', year: '80', article: 'Colosseum' },
      { title: 'Pantheon', artist: 'Unknown, Rome', year: 'c. 126', article: 'Pantheon, Rome' },
      { title: 'Hagia Sophia', artist: 'Anthemius and Isidore', year: '537', article: 'Hagia Sophia' },
      { title: 'Angkor Wat', artist: 'Khmer Empire', year: '12th century', article: 'Angkor Wat' },
      { title: 'Notre-Dame de Paris', artist: 'Unknown', year: '1345', article: 'Notre-Dame de Paris' },
      { title: 'Alhambra', artist: 'Nasrid dynasty', year: '14th century', article: 'Alhambra' },
      { title: 'Forbidden City', artist: 'Kuai Xiang', year: '1420', article: 'Forbidden City' },
      { title: 'Machu Picchu', artist: 'Inca Empire', year: 'c. 1450', article: 'Machu Picchu' },
      { title: 'Taj Mahal', artist: 'Ustad Ahmad Lahori', year: '1653', article: 'Taj Mahal' },
      { title: 'Sagrada Família', artist: 'Antoni Gaudí', year: '1882–', article: 'Sagrada Família' },
      { title: 'Eiffel Tower', artist: 'Gustave Eiffel', year: '1889', article: 'Eiffel Tower' },
      { title: 'Great Mosque of Djenné', artist: 'Ismaila Traoré', year: '1907', article: 'Great Mosque of Djenné' },
      { title: 'Fallingwater', artist: 'Frank Lloyd Wright', year: '1939', article: 'Fallingwater' },
      { title: 'Sydney Opera House', artist: 'Jørn Utzon', year: '1973', article: 'Sydney Opera House' },
    ],
  },
  {
    id: 'literature',
    name: 'Literature',
    color: '#f2cf6b',
    works: [
      { title: 'Epic of Gilgamesh', artist: 'Unknown', year: 'c. 2100 BCE', article: 'Epic of Gilgamesh' },
      { title: 'The Iliad', artist: 'Homer', year: '8th century BCE', article: 'Iliad' },
      { title: 'The Odyssey', artist: 'Homer', year: '8th century BCE', article: 'Odyssey' },
      { title: 'The Analects', artist: 'Confucius', year: 'c. 5th century BCE', article: 'Analects' },
      { title: 'Mahabharata', artist: 'Vyasa (attributed)', year: 'c. 400 BCE – 400 CE', article: 'Mahabharata' },
      { title: 'The Aeneid', artist: 'Virgil', year: '19 BCE', article: 'Aeneid' },
      { title: 'One Thousand and One Nights', artist: 'Unknown', year: 'c. 9th century', article: 'One Thousand and One Nights' },
      { title: 'The Tale of Genji', artist: 'Murasaki Shikibu', year: 'c. 1010', article: 'The Tale of Genji' },
      { title: 'Divine Comedy', artist: 'Dante Alighieri', year: '1320', article: 'Divine Comedy' },
      { title: 'Hamlet', artist: 'William Shakespeare', year: 'c. 1601', article: 'Hamlet' },
      { title: 'Don Quixote', artist: 'Miguel de Cervantes', year: '1605', article: 'Don Quixote' },
      { title: 'Pride and Prejudice', artist: 'Jane Austen', year: '1813', article: 'Pride and Prejudice' },
      { title: 'Crime and Punishment', artist: 'Fyodor Dostoevsky', year: '1866', article: 'Crime and Punishment' },
      { title: 'War and Peace', artist: 'Leo Tolstoy', year: '1869', article: 'War and Peace' },
      { title: 'Ulysses', artist: 'James Joyce', year: '1922', article: 'Ulysses (novel)' },
      { title: 'Things Fall Apart', artist: 'Chinua Achebe', year: '1958', article: 'Things Fall Apart' },
      { title: 'One Hundred Years of Solitude', artist: 'Gabriel García Márquez', year: '1967', article: 'One Hundred Years of Solitude' },
    ],
  },
  {
    id: 'theatre',
    name: 'Theatre',
    color: '#f0a8b8',
    works: [
      { title: 'Oedipus Rex', artist: 'Sophocles', year: 'c. 429 BCE', article: 'Oedipus Rex' },
      { title: 'Medea', artist: 'Euripides', year: '431 BCE', article: 'Medea (play)' },
      { title: 'Shakuntala', artist: 'Kālidāsa', year: 'c. 4th century', article: 'Abhijnanashakuntalam' },
      { title: "A Midsummer Night's Dream", artist: 'William Shakespeare', year: 'c. 1596', article: "A Midsummer Night's Dream" },
      { title: 'Tartuffe', artist: 'Molière', year: '1664', article: 'Tartuffe' },
      { title: 'Faust', artist: 'Johann Wolfgang von Goethe', year: '1808', article: "Goethe's Faust" },
      { title: "A Doll's House", artist: 'Henrik Ibsen', year: '1879', article: "A Doll's House" },
      { title: 'The Cherry Orchard', artist: 'Anton Chekhov', year: '1904', article: 'The Cherry Orchard' },
      { title: 'Death of a Salesman', artist: 'Arthur Miller', year: '1949', article: 'Death of a Salesman' },
      { title: 'Waiting for Godot', artist: 'Samuel Beckett', year: '1953', article: 'Waiting for Godot' },
      { title: 'Hamilton', artist: 'Lin-Manuel Miranda', year: '2015', article: 'Hamilton (musical)' },
    ],
  },
  {
    id: 'music',
    name: 'Music',
    color: '#8fd6ff',
    works: [
      { title: 'Gregorian chant', artist: 'The Western church', year: '9th century', article: 'Gregorian chant' },
      { title: 'The Well-Tempered Clavier', artist: 'Johann Sebastian Bach', year: '1722', article: 'The Well-Tempered Clavier' },
      { title: 'The Four Seasons', artist: 'Antonio Vivaldi', year: '1725', article: 'The Four Seasons (Vivaldi)' },
      { title: 'Goldberg Variations', artist: 'Johann Sebastian Bach', year: '1741', article: 'Goldberg Variations' },
      { title: 'Messiah', artist: 'George Frideric Handel', year: '1741', article: 'Messiah (Handel)' },
      { title: 'Requiem', artist: 'Wolfgang Amadeus Mozart', year: '1791', article: 'Requiem (Mozart)' },
      { title: 'Symphony No. 5', artist: 'Ludwig van Beethoven', year: '1808', article: 'Symphony No. 5 (Beethoven)' },
      { title: 'Symphony No. 9', artist: 'Ludwig van Beethoven', year: '1824', article: 'Symphony No. 9 (Beethoven)' },
      { title: 'Der Ring des Nibelungen', artist: 'Richard Wagner', year: '1876', article: 'Der Ring des Nibelungen' },
      { title: 'Clair de lune', artist: 'Claude Debussy', year: '1905', article: 'Clair de lune (Debussy)' },
      { title: 'The Rite of Spring', artist: 'Igor Stravinsky', year: '1913', article: 'The Rite of Spring' },
      { title: 'Kind of Blue', artist: 'Miles Davis', year: '1959', article: 'Kind of Blue' },
      { title: "Sgt. Pepper's Lonely Hearts Club Band", artist: 'The Beatles', year: '1967', article: "Sgt. Pepper's Lonely Hearts Club Band" },
      { title: "What's Going On", artist: 'Marvin Gaye', year: '1971', article: "What's Going On (album)" },
      { title: 'Thriller', artist: 'Michael Jackson', year: '1982', article: 'Thriller (album)' },
      { title: 'Nevermind', artist: 'Nirvana', year: '1991', article: 'Nevermind' },
    ],
  },
  {
    id: 'film',
    name: 'Film',
    color: '#d8e4f7',
    works: [
      { title: 'Battleship Potemkin', artist: 'Sergei Eisenstein', year: '1925', article: 'Battleship Potemkin' },
      { title: 'Metropolis', artist: 'Fritz Lang', year: '1927', article: 'Metropolis (1927 film)' },
      { title: 'Citizen Kane', artist: 'Orson Welles', year: '1941', article: 'Citizen Kane' },
      { title: 'Casablanca', artist: 'Michael Curtiz', year: '1942', article: 'Casablanca (film)' },
      { title: 'Bicycle Thieves', artist: 'Vittorio De Sica', year: '1948', article: 'Bicycle Thieves' },
      { title: 'Tokyo Story', artist: 'Yasujirō Ozu', year: '1953', article: 'Tokyo Story' },
      { title: 'Seven Samurai', artist: 'Akira Kurosawa', year: '1954', article: 'Seven Samurai' },
      { title: 'Pather Panchali', artist: 'Satyajit Ray', year: '1955', article: 'Pather Panchali' },
      { title: 'Vertigo', artist: 'Alfred Hitchcock', year: '1958', article: 'Vertigo (film)' },
      { title: '2001: A Space Odyssey', artist: 'Stanley Kubrick', year: '1968', article: '2001: A Space Odyssey (film)' },
      { title: 'The Godfather', artist: 'Francis Ford Coppola', year: '1972', article: 'The Godfather' },
      { title: 'Star Wars', artist: 'George Lucas', year: '1977', article: 'Star Wars (film)' },
      { title: 'Pulp Fiction', artist: 'Quentin Tarantino', year: '1994', article: 'Pulp Fiction' },
      { title: 'The Matrix', artist: 'The Wachowskis', year: '1999', article: 'The Matrix' },
      { title: 'Spirited Away', artist: 'Hayao Miyazaki', year: '2001', article: 'Spirited Away' },
      { title: 'Parasite', artist: 'Bong Joon-ho', year: '2019', article: 'Parasite (2019 film)' },
    ],
  },
  {
    id: 'photography',
    name: 'Photography',
    color: '#b9c7d6',
    works: [
      { title: 'View from the Window at Le Gras', artist: 'Nicéphore Niépce', year: '1827', article: 'View from the Window at Le Gras' },
      { title: 'Boulevard du Temple', artist: 'Louis Daguerre', year: '1838', article: 'Boulevard du Temple (photograph)' },
      { title: 'The Horse in Motion', artist: 'Eadweard Muybridge', year: '1878', article: 'The Horse in Motion' },
      { title: 'Migrant Mother', artist: 'Dorothea Lange', year: '1936', article: 'Migrant Mother' },
      { title: 'The Falling Soldier', artist: 'Robert Capa', year: '1936', article: 'The Falling Soldier' },
      { title: 'Raising the Flag on Iwo Jima', artist: 'Joe Rosenthal', year: '1945', article: 'Raising the Flag on Iwo Jima' },
      { title: 'Earthrise', artist: 'William Anders', year: '1968', article: 'Earthrise' },
      { title: 'The Blue Marble', artist: 'The crew of Apollo 17', year: '1972', article: 'The Blue Marble' },
      { title: 'Afghan Girl', artist: 'Steve McCurry', year: '1984', article: 'Afghan Girl' },
      { title: 'Tank Man', artist: 'Jeff Widener', year: '1989', article: 'Tank Man' },
      { title: 'Pale Blue Dot', artist: 'Voyager 1', year: '1990', article: 'Pale Blue Dot' },
    ],
  },
  {
    id: 'fashion',
    name: 'Fashion',
    color: '#f0b7a0',
    works: [
      { title: 'Blue jeans', artist: 'Jacob Davis and Levi Strauss', year: '1873', article: 'Jeans' },
      { title: 'Delphos gown', artist: 'Mariano Fortuny', year: '1907', article: 'Delphos gown' },
      { title: 'Trench coat', artist: 'Thomas Burberry', year: '1912', article: 'Trench coat' },
      { title: 'Little black dress', artist: 'Coco Chanel', year: '1926', article: 'Little black dress' },
      { title: 'Bikini', artist: 'Louis Réard', year: '1946', article: 'Bikini' },
      { title: 'The New Look', artist: 'Christian Dior', year: '1947', article: 'Christian Dior' },
      { title: 'Chanel suit', artist: 'Coco Chanel', year: '1954', article: 'Chanel suit' },
      { title: 'Miniskirt', artist: 'Mary Quant', year: '1964', article: 'Miniskirt' },
      { title: 'Le Smoking', artist: 'Yves Saint Laurent', year: '1966', article: 'Le Smoking' },
      { title: 'Wrap dress', artist: 'Diane von Fürstenberg', year: '1974', article: 'Wrap dress' },
      { title: 'Air Jordan', artist: 'Peter Moore, Nike', year: '1985', article: 'Air Jordan' },
    ],
  },
  {
    id: 'games',
    name: 'Games',
    color: '#86dda3',
    works: [
      { title: 'Spacewar!', artist: 'Steve Russell', year: '1962', article: 'Spacewar!' },
      { title: 'Pong', artist: 'Allan Alcorn, Atari', year: '1972', article: 'Pong' },
      { title: 'Space Invaders', artist: 'Tomohiro Nishikado, Taito', year: '1978', article: 'Space Invaders' },
      { title: 'Pac-Man', artist: 'Toru Iwatani, Namco', year: '1980', article: 'Pac-Man' },
      { title: 'Tetris', artist: 'Alexey Pajitnov', year: '1984', article: 'Tetris' },
      { title: 'Super Mario Bros.', artist: 'Shigeru Miyamoto, Nintendo', year: '1985', article: 'Super Mario Bros.' },
      { title: 'Doom', artist: 'id Software', year: '1993', article: 'Doom (1993 video game)' },
      { title: 'Ocarina of Time', artist: 'Nintendo', year: '1998', article: 'The Legend of Zelda: Ocarina of Time' },
      { title: 'The Sims', artist: 'Will Wright, Maxis', year: '2000', article: 'The Sims (video game)' },
      { title: 'Portal', artist: 'Valve', year: '2007', article: 'Portal (video game)' },
      { title: 'Minecraft', artist: 'Markus Persson, Mojang', year: '2011', article: 'Minecraft' },
      { title: 'Breath of the Wild', artist: 'Nintendo', year: '2017', article: 'The Legend of Zelda: Breath of the Wild' },
    ],
  },
]
