import type { HistoricEvent } from './history'

/**
 * The Inventors' Inlet: a timeline of things people made.
 *
 * The Historical Habitat's timeline is the story of what happened; this is
 * the story of what was built, from the hand axe to the transformer, and it
 * runs on the same spiral with the same eras. A few things appear on both —
 * the wheel, the printing press, the transistor — because they are both a
 * turning point and an invention, and each timeline would be poorer without
 * them.
 */
export const INVENTIONS: readonly HistoricEvent[] = [
  { year: -1700000, label: 'The hand axe', article: 'Hand axe' },
  { year: -400000, label: 'Control of fire', article: 'Control of fire by early humans' },
  { year: -70000, label: 'The bow and arrow', article: 'Bow and arrow' },
  { year: -40000, label: 'The sewing needle', article: 'Sewing needle' },
  { year: -28000, label: 'Pottery', article: 'Pottery' },
  { year: -9000, label: 'Animals are domesticated', article: 'Domestication of animals' },
  { year: -8000, label: 'The brick', article: 'Brick' },
  { year: -6000, label: 'Irrigation', article: 'Irrigation' },
  { year: -5500, label: 'The sail', article: 'Sail' },
  { year: -4000, label: 'The plough', article: 'Plough' },
  { year: -3500, label: 'The wheel', article: 'Wheel' },
  { year: -3500, label: 'Bronze', article: 'Bronze' },
  { year: -3200, label: 'Cuneiform', article: 'Cuneiform' },
  { year: -3000, label: 'Glass', article: 'Glass' },
  { year: -2700, label: 'The abacus', article: 'Abacus' },
  { year: -2600, label: 'Papyrus', article: 'Papyrus' },
  { year: -2000, label: 'The chariot', article: 'Chariot' },
  { year: -1200, label: 'Iron is smelted', article: 'Ferrous metallurgy' },
  { year: -1050, label: 'The alphabet', article: 'Phoenician alphabet' },
  { year: -600, label: 'Coins', article: 'Coin' },
  { year: -500, label: 'The crossbow', article: 'Crossbow' },
  { year: -250, label: "Archimedes' screw", article: "Archimedes' screw" },
  { year: -200, label: 'Roman concrete', article: 'Roman concrete' },
  { year: -150, label: 'The astrolabe', article: 'Astrolabe' },
  { year: -150, label: 'The Antikythera mechanism', article: 'Antikythera mechanism' },
  { year: -50, label: 'Glassblowing', article: 'Glassblowing' },
  { year: 105, label: 'Paper', article: 'Paper' },
  { year: 132, label: 'The seismoscope', article: 'Zhang Heng' },
  { year: 600, label: 'Porcelain', article: 'Porcelain' },
  { year: 650, label: 'The windmill', article: 'Windmill' },
  { year: 800, label: 'Gunpowder', article: 'Gunpowder' },
  { year: 1040, label: 'Movable type', article: 'Movable type' },
  { year: 1040, label: 'The magnetic compass', article: 'Compass' },
  { year: 1286, label: 'Eyeglasses', article: 'Glasses' },
  { year: 1300, label: 'The mechanical clock', article: 'Clock' },
  { year: 1440, label: 'The printing press', article: 'Printing press' },
  { year: 1590, label: 'The microscope', article: 'Microscope' },
  { year: 1596, label: 'The flush toilet', article: 'Flush toilet' },
  { year: 1608, label: 'The telescope', article: 'Telescope' },
  { year: 1614, label: 'Logarithms', article: 'Logarithm' },
  { year: 1642, label: 'The mechanical calculator', article: "Pascal's calculator" },
  { year: 1643, label: 'The barometer', article: 'Barometer' },
  { year: 1656, label: 'The pendulum clock', article: 'Pendulum clock' },
  { year: 1712, label: 'The steam engine', article: 'Steam engine' },
  { year: 1714, label: 'The mercury thermometer', article: 'Mercury-in-glass thermometer' },
  { year: 1752, label: 'The lightning rod', article: 'Lightning rod' },
  { year: 1764, label: 'The spinning jenny', article: 'Spinning jenny' },
  { year: 1776, label: "Watt's steam engine", article: 'Watt steam engine' },
  { year: 1783, label: 'The hot air balloon', article: 'Hot air balloon' },
  { year: 1796, label: 'Lithography', article: 'Lithography' },
  { year: 1800, label: 'The electric battery', article: 'Voltaic pile' },
  { year: 1804, label: 'The steam locomotive', article: 'Steam locomotive' },
  { year: 1816, label: 'The stethoscope', article: 'Stethoscope' },
  { year: 1826, label: 'Photography', article: 'Photography' },
  { year: 1831, label: 'The electric generator', article: 'Electric generator' },
  { year: 1837, label: 'The telegraph', article: 'Electrical telegraph' },
  { year: 1839, label: 'Vulcanised rubber', article: 'Vulcanization' },
  { year: 1846, label: 'Anaesthesia', article: 'Anesthesia' },
  { year: 1856, label: 'Bessemer steel', article: 'Bessemer process' },
  { year: 1859, label: 'The oil well', article: 'Oil well' },
  { year: 1867, label: 'Dynamite', article: 'Dynamite' },
  { year: 1868, label: 'The typewriter', article: 'Typewriter' },
  { year: 1876, label: 'The telephone', article: 'Telephone' },
  { year: 1877, label: 'The phonograph', article: 'Phonograph' },
  { year: 1885, label: 'The safety bicycle', article: 'Safety bicycle' },
  { year: 1895, label: 'Radio', article: 'Radio' },
  { year: 1895, label: 'X-rays', article: 'X-ray' },
  { year: 1907, label: 'Bakelite, the first plastic', article: 'Bakelite' },
  { year: 1909, label: 'The Haber process', article: 'Haber process' },
  { year: 1913, label: 'The assembly line', article: 'Assembly line' },
  { year: 1926, label: 'Television', article: 'Television' },
  { year: 1926, label: 'The liquid-fuelled rocket', article: 'Liquid-propellant rocket' },
  { year: 1935, label: 'Radar', article: 'Radar' },
  { year: 1935, label: 'Nylon', article: 'Nylon' },
  { year: 1938, label: 'The ballpoint pen', article: 'Ballpoint pen' },
  { year: 1942, label: 'The nuclear reactor', article: 'Nuclear reactor' },
  { year: 1945, label: 'The microwave oven', article: 'Microwave oven' },
  { year: 1945, label: 'ENIAC', article: 'ENIAC' },
  { year: 1947, label: 'The transistor', article: 'Transistor' },
  { year: 1950, label: 'The credit card', article: 'Credit card' },
  { year: 1954, label: 'The solar cell', article: 'Solar cell' },
  { year: 1956, label: 'The hard disk drive', article: 'Hard disk drive' },
  { year: 1956, label: 'The shipping container', article: 'Intermodal container' },
  { year: 1958, label: 'The integrated circuit', article: 'Integrated circuit' },
  { year: 1960, label: 'The laser', article: 'Laser' },
  { year: 1960, label: 'The pill', article: 'Combined oral contraceptive pill' },
  { year: 1961, label: 'The industrial robot', article: 'Unimate' },
  { year: 1964, label: 'The computer mouse', article: 'Computer mouse' },
  { year: 1969, label: 'ARPANET', article: 'ARPANET' },
  { year: 1971, label: 'Email', article: 'Email' },
  { year: 1971, label: 'The microprocessor', article: 'Microprocessor' },
  { year: 1973, label: 'The mobile phone', article: 'Mobile phone' },
  { year: 1975, label: 'The digital camera', article: 'Digital camera' },
  { year: 1977, label: 'The personal computer', article: 'Personal computer' },
  { year: 1978, label: 'GPS', article: 'Global Positioning System' },
  { year: 1979, label: 'The Walkman', article: 'Walkman' },
  { year: 1982, label: 'The compact disc', article: 'Compact disc' },
  { year: 1983, label: 'The Internet protocols', article: 'Internet protocol suite' },
  { year: 1989, label: 'The World Wide Web', article: 'World Wide Web' },
  { year: 1991, label: 'The lithium-ion battery', article: 'Lithium-ion battery' },
  { year: 1998, label: 'Google Search', article: 'Google Search' },
  { year: 2001, label: 'Wikipedia', article: 'Wikipedia' },
  { year: 2007, label: 'The smartphone', article: 'Smartphone' },
  { year: 2009, label: 'Bitcoin', article: 'Bitcoin' },
  { year: 2012, label: 'CRISPR gene editing', article: 'CRISPR gene editing' },
  { year: 2017, label: 'The transformer', article: 'Transformer (deep learning architecture)' },
  { year: 2020, label: 'The mRNA vaccine', article: 'MRNA vaccine' },
]
