import type { Figure } from '../scene/familyTree'

/**
 * The Linguistic Lagoon: the world's language families, each as a tree.
 *
 * A figure names its parent, so "Spanish" descends from "Vulgar Latin" and
 * the tree lays itself out. Indo-European is too wide to be one tree that
 * can be read, so its largest branches — Germanic, Romance, Slavic,
 * Indo-Iranian — stand as trees of their own beside an overview of the
 * family's branches. Everywhere the classification is contested (and it
 * usually is somewhere) the tree follows the Wikipedia article it links to,
 * which is where the argument can be read in full.
 */
export type LanguageFamily = {
  id: string
  name: string
  article: string
  color: string
  figures: readonly Figure[]
}

export const FAMILIES: readonly LanguageFamily[] = [
  {
    id: 'indo-european',
    name: 'Indo-European',
    article: 'Indo-European languages',
    color: '#8fe3d9',
    figures: [
      { name: 'Proto-Indo-European', article: 'Proto-Indo-European language' },
      { name: 'Anatolian', article: 'Anatolian languages', parents: ['Proto-Indo-European'] },
      { name: 'Hittite', article: 'Hittite language', parents: ['Anatolian'] },
      { name: 'Tocharian', article: 'Tocharian languages', parents: ['Proto-Indo-European'] },
      { name: 'Hellenic', article: 'Hellenic languages', parents: ['Proto-Indo-European'] },
      { name: 'Greek', article: 'Greek language', parents: ['Hellenic'] },
      { name: 'Italic', article: 'Italic languages', parents: ['Proto-Indo-European'] },
      { name: 'Latin', article: 'Latin', parents: ['Italic'] },
      { name: 'Celtic', article: 'Celtic languages', parents: ['Proto-Indo-European'] },
      { name: 'Irish', article: 'Irish language', parents: ['Celtic'] },
      { name: 'Welsh', article: 'Welsh language', parents: ['Celtic'] },
      { name: 'Germanic', article: 'Germanic languages', parents: ['Proto-Indo-European'] },
      { name: 'Balto-Slavic', article: 'Balto-Slavic languages', parents: ['Proto-Indo-European'] },
      { name: 'Baltic', article: 'Baltic languages', parents: ['Balto-Slavic'] },
      { name: 'Lithuanian', article: 'Lithuanian language', parents: ['Baltic'] },
      { name: 'Slavic', article: 'Slavic languages', parents: ['Balto-Slavic'] },
      { name: 'Indo-Iranian', article: 'Indo-Iranian languages', parents: ['Proto-Indo-European'] },
      { name: 'Armenian', article: 'Armenian language', parents: ['Proto-Indo-European'] },
      { name: 'Albanian', article: 'Albanian language', parents: ['Proto-Indo-European'] },
    ],
  },
  {
    id: 'germanic',
    name: 'Germanic',
    article: 'Germanic languages',
    color: '#b9c7d6',
    figures: [
      { name: 'Proto-Germanic', article: 'Proto-Germanic language' },
      { name: 'West Germanic', article: 'West Germanic languages', parents: ['Proto-Germanic'] },
      { name: 'North Germanic', article: 'North Germanic languages', parents: ['Proto-Germanic'] },
      { name: 'East Germanic', article: 'East Germanic languages', parents: ['Proto-Germanic'] },
      { name: 'Gothic', article: 'Gothic language', parents: ['East Germanic'] },
      { name: 'Old English', article: 'Old English', parents: ['West Germanic'] },
      { name: 'English', article: 'English language', parents: ['Old English'] },
      { name: 'Frisian', article: 'Frisian languages', parents: ['West Germanic'] },
      { name: 'German', article: 'German language', parents: ['West Germanic'] },
      { name: 'Yiddish', article: 'Yiddish', parents: ['German'] },
      { name: 'Dutch', article: 'Dutch language', parents: ['West Germanic'] },
      { name: 'Afrikaans', article: 'Afrikaans', parents: ['Dutch'] },
      { name: 'Old Norse', article: 'Old Norse', parents: ['North Germanic'] },
      { name: 'Swedish', article: 'Swedish language', parents: ['Old Norse'] },
      { name: 'Danish', article: 'Danish language', parents: ['Old Norse'] },
      { name: 'Norwegian', article: 'Norwegian language', parents: ['Old Norse'] },
      { name: 'Icelandic', article: 'Icelandic language', parents: ['Old Norse'] },
    ],
  },
  {
    id: 'romance',
    name: 'Romance',
    article: 'Romance languages',
    color: '#f0b7a0',
    figures: [
      { name: 'Latin', article: 'Latin' },
      { name: 'Vulgar Latin', article: 'Vulgar Latin', parents: ['Latin'] },
      { name: 'Italian', article: 'Italian language', parents: ['Vulgar Latin'] },
      { name: 'Sardinian', article: 'Sardinian language', parents: ['Vulgar Latin'] },
      { name: 'Spanish', article: 'Spanish language', parents: ['Vulgar Latin'] },
      { name: 'Portuguese', article: 'Portuguese language', parents: ['Vulgar Latin'] },
      { name: 'Galician', article: 'Galician language', parents: ['Vulgar Latin'] },
      { name: 'Catalan', article: 'Catalan language', parents: ['Vulgar Latin'] },
      { name: 'Occitan', article: 'Occitan language', parents: ['Vulgar Latin'] },
      { name: 'French', article: 'French language', parents: ['Vulgar Latin'] },
      { name: 'Romanian', article: 'Romanian language', parents: ['Vulgar Latin'] },
    ],
  },
  {
    id: 'slavic',
    name: 'Slavic',
    article: 'Slavic languages',
    color: '#b8c7a0',
    figures: [
      { name: 'Proto-Slavic', article: 'Proto-Slavic language' },
      { name: 'East Slavic', article: 'East Slavic languages', parents: ['Proto-Slavic'] },
      { name: 'West Slavic', article: 'West Slavic languages', parents: ['Proto-Slavic'] },
      { name: 'South Slavic', article: 'South Slavic languages', parents: ['Proto-Slavic'] },
      { name: 'Russian', article: 'Russian language', parents: ['East Slavic'] },
      { name: 'Ukrainian', article: 'Ukrainian language', parents: ['East Slavic'] },
      { name: 'Belarusian', article: 'Belarusian language', parents: ['East Slavic'] },
      { name: 'Polish', article: 'Polish language', parents: ['West Slavic'] },
      { name: 'Czech', article: 'Czech language', parents: ['West Slavic'] },
      { name: 'Slovak', article: 'Slovak language', parents: ['West Slavic'] },
      { name: 'Old Church Slavonic', article: 'Old Church Slavonic', parents: ['South Slavic'] },
      { name: 'Serbo-Croatian', article: 'Serbo-Croatian', parents: ['South Slavic'] },
      { name: 'Bulgarian', article: 'Bulgarian language', parents: ['South Slavic'] },
      { name: 'Macedonian', article: 'Macedonian language', parents: ['South Slavic'] },
      { name: 'Slovene', article: 'Slovene language', parents: ['South Slavic'] },
    ],
  },
  {
    id: 'indo-iranian',
    name: 'Indo-Iranian',
    article: 'Indo-Iranian languages',
    color: '#e6c05a',
    figures: [
      { name: 'Proto-Indo-Iranian', article: 'Proto-Indo-Iranian language' },
      { name: 'Indo-Aryan', article: 'Indo-Aryan languages', parents: ['Proto-Indo-Iranian'] },
      { name: 'Iranian', article: 'Iranian languages', parents: ['Proto-Indo-Iranian'] },
      { name: 'Sanskrit', article: 'Sanskrit', parents: ['Indo-Aryan'] },
      { name: 'Hindustani', article: 'Hindustani language', parents: ['Indo-Aryan'] },
      { name: 'Hindi', article: 'Hindi', parents: ['Hindustani'] },
      { name: 'Urdu', article: 'Urdu', parents: ['Hindustani'] },
      { name: 'Bengali', article: 'Bengali language', parents: ['Indo-Aryan'] },
      { name: 'Punjabi', article: 'Punjabi language', parents: ['Indo-Aryan'] },
      { name: 'Marathi', article: 'Marathi language', parents: ['Indo-Aryan'] },
      { name: 'Gujarati', article: 'Gujarati language', parents: ['Indo-Aryan'] },
      { name: 'Nepali', article: 'Nepali language', parents: ['Indo-Aryan'] },
      { name: 'Sinhala', article: 'Sinhala language', parents: ['Indo-Aryan'] },
      { name: 'Avestan', article: 'Avestan', parents: ['Iranian'] },
      { name: 'Old Persian', article: 'Old Persian', parents: ['Iranian'] },
      { name: 'Persian', article: 'Persian language', parents: ['Old Persian'] },
      { name: 'Pashto', article: 'Pashto', parents: ['Iranian'] },
      { name: 'Kurdish', article: 'Kurdish language', parents: ['Iranian'] },
    ],
  },
  {
    id: 'sino-tibetan',
    name: 'Sino-Tibetan',
    article: 'Sino-Tibetan languages',
    color: '#e8907c',
    figures: [
      { name: 'Proto-Sino-Tibetan', article: 'Proto-Sino-Tibetan language' },
      { name: 'Sinitic', article: 'Sinitic languages', parents: ['Proto-Sino-Tibetan'] },
      { name: 'Tibeto-Burman', article: 'Tibeto-Burman languages', parents: ['Proto-Sino-Tibetan'] },
      { name: 'Old Chinese', article: 'Old Chinese', parents: ['Sinitic'] },
      { name: 'Middle Chinese', article: 'Middle Chinese', parents: ['Old Chinese'] },
      { name: 'Hokkien', article: 'Hokkien', parents: ['Old Chinese'] },
      { name: 'Mandarin', article: 'Mandarin Chinese', parents: ['Middle Chinese'] },
      { name: 'Cantonese', article: 'Cantonese', parents: ['Middle Chinese'] },
      { name: 'Wu', article: 'Wu Chinese', parents: ['Middle Chinese'] },
      { name: 'Hakka', article: 'Hakka Chinese', parents: ['Middle Chinese'] },
      { name: 'Tibetan', article: 'Tibetic languages', parents: ['Tibeto-Burman'] },
      { name: 'Burmese', article: 'Burmese language', parents: ['Tibeto-Burman'] },
      { name: 'Karen', article: 'Karen languages', parents: ['Tibeto-Burman'] },
    ],
  },
  {
    id: 'afroasiatic',
    name: 'Afroasiatic',
    article: 'Afroasiatic languages',
    color: '#d9a066',
    figures: [
      { name: 'Proto-Afroasiatic', article: 'Proto-Afroasiatic language' },
      { name: 'Semitic', article: 'Semitic languages', parents: ['Proto-Afroasiatic'] },
      { name: 'Egyptian', article: 'Egyptian language', parents: ['Proto-Afroasiatic'] },
      { name: 'Berber', article: 'Berber languages', parents: ['Proto-Afroasiatic'] },
      { name: 'Cushitic', article: 'Cushitic languages', parents: ['Proto-Afroasiatic'] },
      { name: 'Chadic', article: 'Chadic languages', parents: ['Proto-Afroasiatic'] },
      { name: 'Akkadian', article: 'Akkadian language', parents: ['Semitic'] },
      { name: 'Arabic', article: 'Arabic', parents: ['Semitic'] },
      { name: 'Hebrew', article: 'Hebrew language', parents: ['Semitic'] },
      { name: 'Aramaic', article: 'Aramaic', parents: ['Semitic'] },
      { name: 'Amharic', article: 'Amharic', parents: ['Semitic'] },
      { name: 'Tigrinya', article: 'Tigrinya language', parents: ['Semitic'] },
      { name: 'Coptic', article: 'Coptic language', parents: ['Egyptian'] },
      { name: 'Tamazight', article: 'Central Atlas Tamazight', parents: ['Berber'] },
      { name: 'Somali', article: 'Somali language', parents: ['Cushitic'] },
      { name: 'Oromo', article: 'Oromo language', parents: ['Cushitic'] },
      { name: 'Hausa', article: 'Hausa language', parents: ['Chadic'] },
    ],
  },
  {
    id: 'niger-congo',
    name: 'Niger–Congo',
    article: 'Niger–Congo languages',
    color: '#9ec27a',
    figures: [
      { name: 'Niger–Congo', article: 'Niger–Congo languages' },
      { name: 'Atlantic–Congo', article: 'Atlantic–Congo languages', parents: ['Niger–Congo'] },
      { name: 'Mande', article: 'Mande languages', parents: ['Niger–Congo'] },
      { name: 'Bantu', article: 'Bantu languages', parents: ['Atlantic–Congo'] },
      { name: 'Yoruba', article: 'Yoruba language', parents: ['Atlantic–Congo'] },
      { name: 'Igbo', article: 'Igbo language', parents: ['Atlantic–Congo'] },
      { name: 'Fula', article: 'Fula language', parents: ['Atlantic–Congo'] },
      { name: 'Wolof', article: 'Wolof language', parents: ['Atlantic–Congo'] },
      { name: 'Akan', article: 'Akan language', parents: ['Atlantic–Congo'] },
      { name: 'Swahili', article: 'Swahili language', parents: ['Bantu'] },
      { name: 'Zulu', article: 'Zulu language', parents: ['Bantu'] },
      { name: 'Xhosa', article: 'Xhosa language', parents: ['Bantu'] },
      { name: 'Shona', article: 'Shona language', parents: ['Bantu'] },
      { name: 'Kinyarwanda', article: 'Kinyarwanda', parents: ['Bantu'] },
      { name: 'Lingala', article: 'Lingala', parents: ['Bantu'] },
      { name: 'Bambara', article: 'Bambara language', parents: ['Mande'] },
    ],
  },
  {
    id: 'austronesian',
    name: 'Austronesian',
    article: 'Austronesian languages',
    color: '#8ab8c6',
    figures: [
      { name: 'Proto-Austronesian', article: 'Proto-Austronesian language' },
      { name: 'Formosan', article: 'Formosan languages', parents: ['Proto-Austronesian'] },
      { name: 'Malayo-Polynesian', article: 'Malayo-Polynesian languages', parents: ['Proto-Austronesian'] },
      { name: 'Malay', article: 'Malay language', parents: ['Malayo-Polynesian'] },
      { name: 'Indonesian', article: 'Indonesian language', parents: ['Malay'] },
      { name: 'Javanese', article: 'Javanese language', parents: ['Malayo-Polynesian'] },
      { name: 'Tagalog', article: 'Tagalog language', parents: ['Malayo-Polynesian'] },
      { name: 'Cebuano', article: 'Cebuano language', parents: ['Malayo-Polynesian'] },
      { name: 'Malagasy', article: 'Malagasy language', parents: ['Malayo-Polynesian'] },
      { name: 'Oceanic', article: 'Oceanic languages', parents: ['Malayo-Polynesian'] },
      { name: 'Fijian', article: 'Fijian language', parents: ['Oceanic'] },
      { name: 'Polynesian', article: 'Polynesian languages', parents: ['Oceanic'] },
      { name: 'Hawaiian', article: 'Hawaiian language', parents: ['Polynesian'] },
      { name: 'Māori', article: 'Māori language', parents: ['Polynesian'] },
      { name: 'Samoan', article: 'Samoan language', parents: ['Polynesian'] },
      { name: 'Tongan', article: 'Tongan language', parents: ['Polynesian'] },
      { name: 'Tahitian', article: 'Tahitian language', parents: ['Polynesian'] },
    ],
  },
  {
    id: 'dravidian',
    name: 'Dravidian',
    article: 'Dravidian languages',
    color: '#e79ad8',
    figures: [
      { name: 'Proto-Dravidian', article: 'Proto-Dravidian language' },
      { name: 'Tamil', article: 'Tamil language', parents: ['Proto-Dravidian'] },
      { name: 'Malayalam', article: 'Malayalam', parents: ['Tamil'] },
      { name: 'Kannada', article: 'Kannada', parents: ['Proto-Dravidian'] },
      { name: 'Telugu', article: 'Telugu language', parents: ['Proto-Dravidian'] },
      { name: 'Tulu', article: 'Tulu language', parents: ['Proto-Dravidian'] },
      { name: 'Gondi', article: 'Gondi language', parents: ['Proto-Dravidian'] },
      { name: 'Brahui', article: 'Brahui language', parents: ['Proto-Dravidian'] },
    ],
  },
  {
    id: 'turkic',
    name: 'Turkic',
    article: 'Turkic languages',
    color: '#c8a15a',
    figures: [
      { name: 'Proto-Turkic', article: 'Proto-Turkic language' },
      { name: 'Oghuz', article: 'Oghuz languages', parents: ['Proto-Turkic'] },
      { name: 'Kipchak', article: 'Kipchak languages', parents: ['Proto-Turkic'] },
      { name: 'Karluk', article: 'Karluk languages', parents: ['Proto-Turkic'] },
      { name: 'Siberian Turkic', article: 'Siberian Turkic languages', parents: ['Proto-Turkic'] },
      { name: 'Chuvash', article: 'Chuvash language', parents: ['Proto-Turkic'] },
      { name: 'Turkish', article: 'Turkish language', parents: ['Oghuz'] },
      { name: 'Azerbaijani', article: 'Azerbaijani language', parents: ['Oghuz'] },
      { name: 'Turkmen', article: 'Turkmen language', parents: ['Oghuz'] },
      { name: 'Kazakh', article: 'Kazakh language', parents: ['Kipchak'] },
      { name: 'Kyrgyz', article: 'Kyrgyz language', parents: ['Kipchak'] },
      { name: 'Tatar', article: 'Tatar language', parents: ['Kipchak'] },
      { name: 'Uzbek', article: 'Uzbek language', parents: ['Karluk'] },
      { name: 'Uyghur', article: 'Uyghur language', parents: ['Karluk'] },
      { name: 'Yakut', article: 'Yakut language', parents: ['Siberian Turkic'] },
    ],
  },
  {
    id: 'uralic',
    name: 'Uralic',
    article: 'Uralic languages',
    color: '#a9c8e8',
    figures: [
      { name: 'Proto-Uralic', article: 'Proto-Uralic language' },
      { name: 'Finnic', article: 'Finnic languages', parents: ['Proto-Uralic'] },
      { name: 'Sámi', article: 'Sámi languages', parents: ['Proto-Uralic'] },
      { name: 'Permic', article: 'Permic languages', parents: ['Proto-Uralic'] },
      { name: 'Ugric', article: 'Ugric languages', parents: ['Proto-Uralic'] },
      { name: 'Samoyedic', article: 'Samoyedic languages', parents: ['Proto-Uralic'] },
      { name: 'Finnish', article: 'Finnish language', parents: ['Finnic'] },
      { name: 'Estonian', article: 'Estonian language', parents: ['Finnic'] },
      { name: 'Karelian', article: 'Karelian language', parents: ['Finnic'] },
      { name: 'Northern Sámi', article: 'Northern Sámi', parents: ['Sámi'] },
      { name: 'Komi', article: 'Komi language', parents: ['Permic'] },
      { name: 'Udmurt', article: 'Udmurt language', parents: ['Permic'] },
      { name: 'Hungarian', article: 'Hungarian language', parents: ['Ugric'] },
      { name: 'Khanty', article: 'Khanty language', parents: ['Ugric'] },
      { name: 'Nenets', article: 'Nenets languages', parents: ['Samoyedic'] },
    ],
  },
  {
    id: 'japonic',
    name: 'Japonic',
    article: 'Japonic languages',
    color: '#e6b4b4',
    figures: [
      { name: 'Proto-Japonic', article: 'Proto-Japonic language' },
      { name: 'Old Japanese', article: 'Old Japanese', parents: ['Proto-Japonic'] },
      { name: 'Japanese', article: 'Japanese language', parents: ['Old Japanese'] },
      { name: 'Ryukyuan', article: 'Ryukyuan languages', parents: ['Proto-Japonic'] },
      { name: 'Okinawan', article: 'Okinawan language', parents: ['Ryukyuan'] },
      { name: 'Amami', article: 'Amami Ōshima language', parents: ['Ryukyuan'] },
    ],
  },
  {
    id: 'koreanic',
    name: 'Koreanic',
    article: 'Koreanic languages',
    color: '#c6a27a',
    figures: [
      { name: 'Proto-Koreanic', article: 'Proto-Koreanic language' },
      { name: 'Middle Korean', article: 'Middle Korean', parents: ['Proto-Koreanic'] },
      { name: 'Korean', article: 'Korean language', parents: ['Middle Korean'] },
      { name: 'Jeju', article: 'Jeju language', parents: ['Middle Korean'] },
    ],
  },
  {
    id: 'austroasiatic',
    name: 'Austroasiatic',
    article: 'Austroasiatic languages',
    color: '#7ccf8e',
    figures: [
      { name: 'Proto-Austroasiatic', article: 'Proto-Austroasiatic language' },
      { name: 'Vietic', article: 'Vietic languages', parents: ['Proto-Austroasiatic'] },
      { name: 'Vietnamese', article: 'Vietnamese language', parents: ['Vietic'] },
      { name: 'Khmer', article: 'Khmer language', parents: ['Proto-Austroasiatic'] },
      { name: 'Mon', article: 'Mon language', parents: ['Proto-Austroasiatic'] },
      { name: 'Khasi', article: 'Khasi language', parents: ['Proto-Austroasiatic'] },
      { name: 'Munda', article: 'Munda languages', parents: ['Proto-Austroasiatic'] },
      { name: 'Santali', article: 'Santali language', parents: ['Munda'] },
    ],
  },
  {
    id: 'kra-dai',
    name: 'Kra–Dai',
    article: 'Kra–Dai languages',
    color: '#f2cf6b',
    figures: [
      { name: 'Kra–Dai', article: 'Kra–Dai languages' },
      { name: 'Tai', article: 'Tai languages', parents: ['Kra–Dai'] },
      { name: 'Kra', article: 'Kra languages', parents: ['Kra–Dai'] },
      { name: 'Hlai', article: 'Hlai languages', parents: ['Kra–Dai'] },
      { name: 'Thai', article: 'Thai language', parents: ['Tai'] },
      { name: 'Lao', article: 'Lao language', parents: ['Tai'] },
      { name: 'Shan', article: 'Shan language', parents: ['Tai'] },
      { name: 'Zhuang', article: 'Zhuang languages', parents: ['Tai'] },
    ],
  },
]
