import type { Figure } from '../scene/familyTree'

/**
 * The Biological Bayou: the tree of life, in five trees.
 *
 * One tree of everything would be sixty rows deep and a hundred wide, so it
 * is cut where a naturalist would cut it: the domains and kingdoms at the
 * top, then the animals without backbones, the animals with, the plants, and
 * the fungi. The figures are ranks a general reader knows — insects, sharks,
 * grasses — with a few species at the tips to make them concrete. Where the
 * modern cladistics and the familiar names disagree (birds are dinosaurs;
 * whales are hoofed mammals), the tree goes with the cladistics and the
 * article explains.
 */
export type LifeGroup = {
  id: string
  name: string
  article: string
  color: string
  figures: readonly Figure[]
}

export const LIFE: readonly LifeGroup[] = [
  {
    id: 'domains',
    name: 'Domains of life',
    article: 'Life',
    color: '#a6e37a',
    figures: [
      { name: 'Life', article: 'Life' },
      { name: 'Bacteria', article: 'Bacteria', parents: ['Life'] },
      { name: 'Archaea', article: 'Archaea', parents: ['Life'] },
      { name: 'Eukaryotes', article: 'Eukaryote', parents: ['Life'] },
      { name: 'Cyanobacteria', article: 'Cyanobacteria', parents: ['Bacteria'] },
      { name: 'E. coli', article: 'Escherichia coli', parents: ['Bacteria'] },
      { name: 'Methanogens', article: 'Methanogen', parents: ['Archaea'] },
      { name: 'Haloarchaea', article: 'Haloarchaea', parents: ['Archaea'] },
      { name: 'Animals', article: 'Animal', parents: ['Eukaryotes'] },
      { name: 'Plants', article: 'Plant', parents: ['Eukaryotes'] },
      { name: 'Fungi', article: 'Fungus', parents: ['Eukaryotes'] },
      { name: 'Protists', article: 'Protist', parents: ['Eukaryotes'] },
      { name: 'Algae', article: 'Algae', parents: ['Protists'] },
      { name: 'Amoebae', article: 'Amoeba', parents: ['Protists'] },
      { name: 'Diatoms', article: 'Diatom', parents: ['Protists'] },
      { name: 'Slime moulds', article: 'Slime mold', parents: ['Protists'] },
    ],
  },
  {
    id: 'invertebrates',
    name: 'Invertebrates',
    article: 'Invertebrate',
    color: '#e8a06a',
    figures: [
      { name: 'Animals', article: 'Animal' },
      { name: 'Sponges', article: 'Sponge', parents: ['Animals'] },
      { name: 'Cnidarians', article: 'Cnidaria', parents: ['Animals'] },
      { name: 'Jellyfish', article: 'Jellyfish', parents: ['Cnidarians'] },
      { name: 'Corals', article: 'Coral', parents: ['Cnidarians'] },
      { name: 'Arthropods', article: 'Arthropod', parents: ['Animals'] },
      { name: 'Insects', article: 'Insect', parents: ['Arthropods'] },
      { name: 'Beetles', article: 'Beetle', parents: ['Insects'] },
      { name: 'Butterflies', article: 'Butterfly', parents: ['Insects'] },
      { name: 'Ants', article: 'Ant', parents: ['Insects'] },
      { name: 'Bees', article: 'Bee', parents: ['Insects'] },
      { name: 'Arachnids', article: 'Arachnid', parents: ['Arthropods'] },
      { name: 'Spiders', article: 'Spider', parents: ['Arachnids'] },
      { name: 'Scorpions', article: 'Scorpion', parents: ['Arachnids'] },
      { name: 'Crustaceans', article: 'Crustacean', parents: ['Arthropods'] },
      { name: 'Crabs', article: 'Crab', parents: ['Crustaceans'] },
      { name: 'Lobsters', article: 'Lobster', parents: ['Crustaceans'] },
      { name: 'Molluscs', article: 'Mollusca', parents: ['Animals'] },
      { name: 'Cephalopods', article: 'Cephalopod', parents: ['Molluscs'] },
      { name: 'Octopuses', article: 'Octopus', parents: ['Cephalopods'] },
      { name: 'Squid', article: 'Squid', parents: ['Cephalopods'] },
      { name: 'Snails', article: 'Snail', parents: ['Molluscs'] },
      { name: 'Bivalves', article: 'Bivalvia', parents: ['Molluscs'] },
      { name: 'Echinoderms', article: 'Echinoderm', parents: ['Animals'] },
      { name: 'Starfish', article: 'Starfish', parents: ['Echinoderms'] },
      { name: 'Sea urchins', article: 'Sea urchin', parents: ['Echinoderms'] },
      { name: 'Annelids', article: 'Annelid', parents: ['Animals'] },
      { name: 'Earthworms', article: 'Earthworm', parents: ['Annelids'] },
    ],
  },
  {
    id: 'vertebrates',
    name: 'Vertebrates',
    article: 'Vertebrate',
    color: '#8fd6ff',
    figures: [
      { name: 'Vertebrates', article: 'Vertebrate' },
      { name: 'Fish', article: 'Fish', parents: ['Vertebrates'] },
      { name: 'Sharks', article: 'Shark', parents: ['Fish'] },
      { name: 'Bony fish', article: 'Osteichthyes', parents: ['Fish'] },
      { name: 'Coelacanths', article: 'Coelacanth', parents: ['Bony fish'] },
      { name: 'Tetrapods', article: 'Tetrapod', parents: ['Bony fish'] },
      { name: 'Amphibians', article: 'Amphibian', parents: ['Tetrapods'] },
      { name: 'Frogs', article: 'Frog', parents: ['Amphibians'] },
      { name: 'Salamanders', article: 'Salamander', parents: ['Amphibians'] },
      { name: 'Reptiles', article: 'Reptile', parents: ['Tetrapods'] },
      { name: 'Lizards', article: 'Lizard', parents: ['Reptiles'] },
      { name: 'Snakes', article: 'Snake', parents: ['Reptiles'] },
      { name: 'Turtles', article: 'Turtle', parents: ['Reptiles'] },
      { name: 'Crocodiles', article: 'Crocodilia', parents: ['Reptiles'] },
      { name: 'Dinosaurs', article: 'Dinosaur', parents: ['Reptiles'] },
      { name: 'Birds', article: 'Bird', parents: ['Dinosaurs'] },
      { name: 'Eagles', article: 'Eagle', parents: ['Birds'] },
      { name: 'Penguins', article: 'Penguin', parents: ['Birds'] },
      { name: 'Hummingbirds', article: 'Hummingbird', parents: ['Birds'] },
      { name: 'Mammals', article: 'Mammal', parents: ['Tetrapods'] },
      { name: 'Monotremes', article: 'Monotreme', parents: ['Mammals'] },
      { name: 'Platypus', article: 'Platypus', parents: ['Monotremes'] },
      { name: 'Marsupials', article: 'Marsupial', parents: ['Mammals'] },
      { name: 'Kangaroos', article: 'Kangaroo', parents: ['Marsupials'] },
      { name: 'Placentals', article: 'Placentalia', parents: ['Mammals'] },
      { name: 'Primates', article: 'Primate', parents: ['Placentals'] },
      { name: 'Humans', article: 'Human', parents: ['Primates'] },
      { name: 'Chimpanzees', article: 'Chimpanzee', parents: ['Primates'] },
      { name: 'Whales', article: 'Cetacea', parents: ['Placentals'] },
      { name: 'Blue whale', article: 'Blue whale', parents: ['Whales'] },
      { name: 'Bats', article: 'Bat', parents: ['Placentals'] },
      { name: 'Elephants', article: 'Elephant', parents: ['Placentals'] },
      { name: 'Carnivorans', article: 'Carnivora', parents: ['Placentals'] },
      { name: 'Dogs', article: 'Dog', parents: ['Carnivorans'] },
      { name: 'Cats', article: 'Cat', parents: ['Carnivorans'] },
      { name: 'Rodents', article: 'Rodent', parents: ['Placentals'] },
    ],
  },
  {
    id: 'plants',
    name: 'Plants',
    article: 'Plant',
    color: '#7ccf8e',
    figures: [
      { name: 'Plants', article: 'Plant' },
      { name: 'Green algae', article: 'Green algae', parents: ['Plants'] },
      { name: 'Land plants', article: 'Embryophyte', parents: ['Plants'] },
      { name: 'Mosses', article: 'Moss', parents: ['Land plants'] },
      { name: 'Ferns', article: 'Fern', parents: ['Land plants'] },
      { name: 'Seed plants', article: 'Spermatophyte', parents: ['Land plants'] },
      { name: 'Gymnosperms', article: 'Gymnosperm', parents: ['Seed plants'] },
      { name: 'Conifers', article: 'Conifer', parents: ['Gymnosperms'] },
      { name: 'Pines', article: 'Pine', parents: ['Conifers'] },
      { name: 'Redwoods', article: 'Sequoioideae', parents: ['Conifers'] },
      { name: 'Ginkgo', article: 'Ginkgo biloba', parents: ['Gymnosperms'] },
      { name: 'Flowering plants', article: 'Flowering plant', parents: ['Seed plants'] },
      { name: 'Monocots', article: 'Monocotyledon', parents: ['Flowering plants'] },
      { name: 'Grasses', article: 'Poaceae', parents: ['Monocots'] },
      { name: 'Rice', article: 'Rice', parents: ['Grasses'] },
      { name: 'Wheat', article: 'Wheat', parents: ['Grasses'] },
      { name: 'Bamboo', article: 'Bamboo', parents: ['Grasses'] },
      { name: 'Orchids', article: 'Orchidaceae', parents: ['Monocots'] },
      { name: 'Palms', article: 'Arecaceae', parents: ['Monocots'] },
      { name: 'Eudicots', article: 'Eudicots', parents: ['Flowering plants'] },
      { name: 'Roses', article: 'Rose', parents: ['Eudicots'] },
      { name: 'Oaks', article: 'Oak', parents: ['Eudicots'] },
      { name: 'Sunflowers', article: 'Helianthus', parents: ['Eudicots'] },
      { name: 'Cacti', article: 'Cactus', parents: ['Eudicots'] },
      { name: 'Legumes', article: 'Fabaceae', parents: ['Eudicots'] },
      { name: 'Nightshades', article: 'Solanaceae', parents: ['Eudicots'] },
      { name: 'Tomato', article: 'Tomato', parents: ['Nightshades'] },
      { name: 'Potato', article: 'Potato', parents: ['Nightshades'] },
    ],
  },
  {
    id: 'fungi',
    name: 'Fungi',
    article: 'Fungus',
    color: '#d9a066',
    figures: [
      { name: 'Fungi', article: 'Fungus' },
      { name: 'Chytrids', article: 'Chytridiomycota', parents: ['Fungi'] },
      { name: 'Moulds', article: 'Mold', parents: ['Fungi'] },
      { name: 'Basidiomycetes', article: 'Basidiomycota', parents: ['Fungi'] },
      { name: 'Mushrooms', article: 'Mushroom', parents: ['Basidiomycetes'] },
      { name: 'Rusts', article: 'Rust (fungus)', parents: ['Basidiomycetes'] },
      { name: 'Ascomycetes', article: 'Ascomycota', parents: ['Fungi'] },
      { name: 'Yeasts', article: 'Yeast', parents: ['Ascomycetes'] },
      { name: 'Penicillium', article: 'Penicillium', parents: ['Ascomycetes'] },
      { name: 'Truffles', article: 'Truffle', parents: ['Ascomycetes'] },
      { name: 'Morels', article: 'Morchella', parents: ['Ascomycetes'] },
      { name: 'Lichens', article: 'Lichen', parents: ['Ascomycetes'] },
    ],
  },
]
