/**
 * The Mythological Monument's lore: the legends the gods star in, and the
 * creatures that stalk them. The pantheons themselves are in pantheons.ts.
 *
 * `origin` names the tradition, which is what the card's kicker says.
 */
export type Lore = { name: string; article: string; origin: string }

export const LEGENDS: readonly Lore[] = [
  { name: 'Enūma Eliš', article: 'Enūma Eliš', origin: 'Babylonian' },
  { name: 'The Osiris myth', article: 'Osiris myth', origin: 'Egyptian' },
  { name: 'The Trojan War', article: 'Trojan War', origin: 'Greek' },
  { name: 'The Labours of Heracles', article: 'Labours of Hercules', origin: 'Greek' },
  { name: 'Prometheus', article: 'Prometheus', origin: 'Greek' },
  { name: 'Orpheus and Eurydice', article: 'Orpheus', origin: 'Greek' },
  { name: "Pandora's box", article: 'Pandora', origin: 'Greek' },
  { name: 'The Argonauts', article: 'Argonauts', origin: 'Greek' },
  { name: 'Icarus', article: 'Icarus', origin: 'Greek' },
  { name: 'Sisyphus', article: 'Sisyphus', origin: 'Greek' },
  { name: 'Atlantis', article: 'Atlantis', origin: 'Greek' },
  { name: 'Ragnarök', article: 'Ragnarök', origin: 'Norse' },
  { name: 'The Völsunga saga', article: 'Völsunga saga', origin: 'Norse' },
  { name: 'Beowulf', article: 'Beowulf', origin: 'Anglo-Saxon' },
  { name: 'King Arthur', article: 'King Arthur', origin: 'British' },
  { name: 'Táin Bó Cúailnge', article: 'Táin Bó Cúailnge', origin: 'Irish' },
  { name: 'The Kalevala', article: 'Kalevala', origin: 'Finnish' },
  { name: 'The Ramayana', article: 'Ramayana', origin: 'Hindu' },
  { name: 'The churning of the ocean', article: 'Samudra Manthana', origin: 'Hindu' },
  { name: 'The Shahnameh', article: 'Shahnameh', origin: 'Persian' },
  { name: 'Journey to the West', article: 'Journey to the West', origin: 'Chinese' },
  { name: 'Legend of the White Snake', article: 'Legend of the White Snake', origin: 'Chinese' },
  { name: 'Amaterasu and the cave', article: 'Amano-Iwato', origin: 'Japanese' },
  { name: 'The Popol Vuh', article: 'Popol Vuh', origin: 'Maya' },
  { name: 'The Five Suns', article: 'Five Suns', origin: 'Aztec' },
  { name: 'The Epic of Sundiata', article: 'Epic of Sundiata', origin: 'Mandinka' },
  { name: 'Anansi', article: 'Anansi', origin: 'Akan' },
  { name: 'The Dreamtime', article: 'Dreamtime', origin: 'Aboriginal Australian' },
  { name: 'The flood', article: 'Flood myth', origin: 'Many traditions' },
]

export const CREATURES: readonly Lore[] = [
  { name: 'Dragon', article: 'Dragon', origin: 'Many traditions' },
  { name: 'Phoenix', article: 'Phoenix (mythology)', origin: 'Greek and Egyptian' },
  { name: 'Sphinx', article: 'Sphinx', origin: 'Egyptian and Greek' },
  { name: 'Minotaur', article: 'Minotaur', origin: 'Greek' },
  { name: 'Medusa', article: 'Medusa', origin: 'Greek' },
  { name: 'Centaur', article: 'Centaur', origin: 'Greek' },
  { name: 'Cyclops', article: 'Cyclopes', origin: 'Greek' },
  { name: 'Cerberus', article: 'Cerberus', origin: 'Greek' },
  { name: 'Pegasus', article: 'Pegasus', origin: 'Greek' },
  { name: 'Chimera', article: 'Chimera (mythology)', origin: 'Greek' },
  { name: 'Hydra', article: 'Lernaean Hydra', origin: 'Greek' },
  { name: 'Siren', article: 'Siren (mythology)', origin: 'Greek' },
  { name: 'Griffin', article: 'Griffin', origin: 'Greek and Persian' },
  { name: 'Unicorn', article: 'Unicorn', origin: 'European' },
  { name: 'Basilisk', article: 'Basilisk', origin: 'European' },
  { name: 'Werewolf', article: 'Werewolf', origin: 'European' },
  { name: 'Vampire', article: 'Vampire', origin: 'European' },
  { name: 'Troll', article: 'Troll', origin: 'Norse' },
  { name: 'Fenrir', article: 'Fenrir', origin: 'Norse' },
  { name: 'Jörmungandr', article: 'Jörmungandr', origin: 'Norse' },
  { name: 'Kraken', article: 'Kraken', origin: 'Norse' },
  { name: 'Banshee', article: 'Banshee', origin: 'Irish' },
  { name: 'Golem', article: 'Golem', origin: 'Jewish' },
  { name: 'Leviathan', article: 'Leviathan', origin: 'Hebrew' },
  { name: 'Jinn', article: 'Jinn', origin: 'Arabian' },
  { name: 'Roc', article: 'Roc (mythology)', origin: 'Arabian' },
  { name: 'Garuda', article: 'Garuda', origin: 'Hindu and Buddhist' },
  { name: 'Nāga', article: 'Nāga', origin: 'Hindu and Buddhist' },
  { name: 'Qilin', article: 'Qilin', origin: 'Chinese' },
  { name: 'Kitsune', article: 'Kitsune', origin: 'Japanese' },
  { name: 'Tengu', article: 'Tengu', origin: 'Japanese' },
  { name: 'Yeti', article: 'Yeti', origin: 'Himalayan' },
  { name: 'Thunderbird', article: 'Thunderbird (mythology)', origin: 'Native American' },
  { name: 'Wendigo', article: 'Wendigo', origin: 'Algonquian' },
  { name: 'Mermaid', article: 'Mermaid', origin: 'Many traditions' },
  { name: 'Manticore', article: 'Manticore', origin: 'Persian' },
]
