/**
 * The Ideology Isles: fourteen mythologies, each with the family tree of its gods.
 *
 * A deity names its parents by name, within the same pantheon. From that the
 * tree lays itself out: a figure's generation is one below its parents', and a
 * figure with no parents but with children — a consort who marries into the
 * line — is placed level with its partner rather than up with the primordials.
 * Roots with neither parents nor children (Tlaloc, Thoth) are shown as
 * members of the pantheon standing apart, which is what they are.
 *
 * Every line here follows one named source tradition rather than a blend:
 * Hesiod for the Greeks, the Prose Edda for the Norse, the Heliopolitan Ennead
 * for Egypt, the Enūma Eliš for Babylon, the Kojiki for Japan, the Puranas for
 * India. Where traditions genuinely conflict — Huitzilopochtli has two
 * accounts of his birth — one is chosen and the other is not drawn, because a
 * family tree with two mothers for one god is not a tree. The Wikipedia
 * article each figure links to carries the full picture.
 */
export type Deity = { name: string; article: string; parents?: readonly string[] }

export type Pantheon = {
  id: string
  name: string
  article: string
  /** The islet's colour, and the tint of its orbs. */
  color: string
  deities: readonly Deity[]
}

export const PANTHEONS: readonly Pantheon[] = [
  {
    id: 'greek',
    name: 'Greek',
    article: 'Greek mythology',
    color: '#e8d8a6',
    deities: [
      { name: 'Chaos', article: 'Chaos (cosmogony)' },
      { name: 'Gaia', article: 'Gaia' },
      { name: 'Tartarus', article: 'Tartarus' },
      { name: 'Eros', article: 'Eros' },
      { name: 'Nyx', article: 'Nyx', parents: ['Chaos'] },
      { name: 'Erebus', article: 'Erebus', parents: ['Chaos'] },
      { name: 'Uranus', article: 'Uranus (mythology)', parents: ['Gaia'] },
      { name: 'Cronus', article: 'Cronus', parents: ['Gaia', 'Uranus'] },
      { name: 'Rhea', article: 'Rhea (mythology)', parents: ['Gaia', 'Uranus'] },
      { name: 'Oceanus', article: 'Oceanus', parents: ['Gaia', 'Uranus'] },
      { name: 'Hyperion', article: 'Hyperion (Titan)', parents: ['Gaia', 'Uranus'] },
      { name: 'Themis', article: 'Themis', parents: ['Gaia', 'Uranus'] },
      { name: 'Aphrodite', article: 'Aphrodite', parents: ['Uranus'] },
      { name: 'Helios', article: 'Helios', parents: ['Hyperion'] },
      { name: 'Selene', article: 'Selene', parents: ['Hyperion'] },
      { name: 'Zeus', article: 'Zeus', parents: ['Cronus', 'Rhea'] },
      { name: 'Hera', article: 'Hera', parents: ['Cronus', 'Rhea'] },
      { name: 'Poseidon', article: 'Poseidon', parents: ['Cronus', 'Rhea'] },
      { name: 'Hades', article: 'Hades', parents: ['Cronus', 'Rhea'] },
      { name: 'Demeter', article: 'Demeter', parents: ['Cronus', 'Rhea'] },
      { name: 'Hestia', article: 'Hestia', parents: ['Cronus', 'Rhea'] },
      { name: 'Leto', article: 'Leto' },
      { name: 'Metis', article: 'Metis (mythology)' },
      { name: 'Maia', article: 'Maia' },
      { name: 'Semele', article: 'Semele' },
      { name: 'Ares', article: 'Ares', parents: ['Zeus', 'Hera'] },
      { name: 'Hephaestus', article: 'Hephaestus', parents: ['Zeus', 'Hera'] },
      { name: 'Hebe', article: 'Hebe (mythology)', parents: ['Zeus', 'Hera'] },
      { name: 'Apollo', article: 'Apollo', parents: ['Zeus', 'Leto'] },
      { name: 'Artemis', article: 'Artemis', parents: ['Zeus', 'Leto'] },
      { name: 'Athena', article: 'Athena', parents: ['Zeus', 'Metis'] },
      { name: 'Hermes', article: 'Hermes', parents: ['Zeus', 'Maia'] },
      { name: 'Dionysus', article: 'Dionysus', parents: ['Zeus', 'Semele'] },
      { name: 'Persephone', article: 'Persephone', parents: ['Zeus', 'Demeter'] },
    ],
  },
  {
    id: 'norse',
    name: 'Norse',
    article: 'Norse mythology',
    color: '#b9c7d6',
    deities: [
      { name: 'Ymir', article: 'Ymir' },
      { name: 'Búri', article: 'Búri' },
      { name: 'Borr', article: 'Borr', parents: ['Búri'] },
      { name: 'Bestla', article: 'Bestla' },
      { name: 'Odin', article: 'Odin', parents: ['Borr', 'Bestla'] },
      { name: 'Vili', article: 'Vili and Vé', parents: ['Borr', 'Bestla'] },
      { name: 'Vé', article: 'Vili and Vé', parents: ['Borr', 'Bestla'] },
      { name: 'Frigg', article: 'Frigg' },
      { name: 'Jörð', article: 'Jörð' },
      { name: 'Thor', article: 'Thor', parents: ['Odin', 'Jörð'] },
      { name: 'Baldr', article: 'Baldr', parents: ['Odin', 'Frigg'] },
      { name: 'Höðr', article: 'Höðr', parents: ['Odin', 'Frigg'] },
      { name: 'Víðarr', article: 'Víðarr', parents: ['Odin'] },
      { name: 'Váli', article: 'Váli', parents: ['Odin'] },
      { name: 'Bragi', article: 'Bragi', parents: ['Odin'] },
      { name: 'Týr', article: 'Týr', parents: ['Odin'] },
      { name: 'Sif', article: 'Sif' },
      { name: 'Þrúðr', article: 'Þrúðr', parents: ['Thor', 'Sif'] },
      { name: 'Magni', article: 'Móði and Magni', parents: ['Thor'] },
      { name: 'Móði', article: 'Móði and Magni', parents: ['Thor'] },
      { name: 'Nanna', article: 'Nanna (Norse deity)' },
      { name: 'Forseti', article: 'Forseti', parents: ['Baldr', 'Nanna'] },
      { name: 'Njörðr', article: 'Njörðr' },
      { name: 'Freyr', article: 'Freyr', parents: ['Njörðr'] },
      { name: 'Freyja', article: 'Freyja', parents: ['Njörðr'] },
      { name: 'Heimdallr', article: 'Heimdallr' },
      { name: 'Loki', article: 'Loki' },
      { name: 'Angrboða', article: 'Angrboða' },
      { name: 'Hel', article: 'Hel (being)', parents: ['Loki', 'Angrboða'] },
      { name: 'Fenrir', article: 'Fenrir', parents: ['Loki', 'Angrboða'] },
      { name: 'Jörmungandr', article: 'Jörmungandr', parents: ['Loki', 'Angrboða'] },
      { name: 'Sleipnir', article: 'Sleipnir', parents: ['Loki'] },
    ],
  },
  {
    id: 'egyptian',
    name: 'Egyptian',
    article: 'Ancient Egyptian deities',
    color: '#d8b46a',
    deities: [
      { name: 'Nun', article: 'Nu (mythology)' },
      { name: 'Atum', article: 'Atum', parents: ['Nun'] },
      { name: 'Ra', article: 'Ra' },
      { name: 'Shu', article: 'Shu (Egyptian god)', parents: ['Atum'] },
      { name: 'Tefnut', article: 'Tefnut', parents: ['Atum'] },
      { name: 'Geb', article: 'Geb', parents: ['Shu', 'Tefnut'] },
      { name: 'Nut', article: 'Nut (goddess)', parents: ['Shu', 'Tefnut'] },
      { name: 'Osiris', article: 'Osiris', parents: ['Geb', 'Nut'] },
      { name: 'Isis', article: 'Isis', parents: ['Geb', 'Nut'] },
      { name: 'Set', article: 'Set (deity)', parents: ['Geb', 'Nut'] },
      { name: 'Nephthys', article: 'Nephthys', parents: ['Geb', 'Nut'] },
      { name: 'Horus', article: 'Horus', parents: ['Osiris', 'Isis'] },
      { name: 'Anubis', article: 'Anubis', parents: ['Set', 'Nephthys'] },
      { name: 'Hathor', article: 'Hathor', parents: ['Ra'] },
      { name: 'Bastet', article: 'Bastet', parents: ['Ra'] },
      { name: 'Sekhmet', article: 'Sekhmet', parents: ['Ra'] },
      { name: 'Maat', article: 'Maat', parents: ['Ra'] },
      { name: 'Thoth', article: 'Thoth' },
      { name: 'Ptah', article: 'Ptah' },
      { name: 'Amun', article: 'Amun' },
      { name: 'Mut', article: 'Mut' },
      { name: 'Khonsu', article: 'Khonsu', parents: ['Amun', 'Mut'] },
    ],
  },
  {
    id: 'mesopotamian',
    name: 'Mesopotamian',
    article: 'Ancient Mesopotamian religion',
    color: '#c6a27a',
    deities: [
      { name: 'Apsu', article: 'Abzu' },
      { name: 'Tiamat', article: 'Tiamat' },
      { name: 'Lahmu', article: 'Lahmu', parents: ['Apsu', 'Tiamat'] },
      { name: 'Lahamu', article: 'Lahamu', parents: ['Apsu', 'Tiamat'] },
      { name: 'Anshar', article: 'Anshar', parents: ['Lahmu', 'Lahamu'] },
      { name: 'Kishar', article: 'Kishar', parents: ['Lahmu', 'Lahamu'] },
      { name: 'Anu', article: 'Anu', parents: ['Anshar', 'Kishar'] },
      { name: 'Ki', article: 'Ki (goddess)' },
      { name: 'Enlil', article: 'Enlil', parents: ['Anu', 'Ki'] },
      { name: 'Enki', article: 'Enki', parents: ['Anu'] },
      { name: 'Ninlil', article: 'Ninlil' },
      { name: 'Nanna', article: 'Sin (mythology)', parents: ['Enlil', 'Ninlil'] },
      { name: 'Ninurta', article: 'Ninurta', parents: ['Enlil'] },
      { name: 'Nergal', article: 'Nergal', parents: ['Enlil', 'Ninlil'] },
      { name: 'Ningal', article: 'Ningal' },
      { name: 'Utu', article: 'Utu', parents: ['Nanna', 'Ningal'] },
      { name: 'Inanna', article: 'Inanna', parents: ['Nanna', 'Ningal'] },
      { name: 'Ereshkigal', article: 'Ereshkigal', parents: ['Nanna', 'Ningal'] },
      { name: 'Dumuzid', article: 'Dumuzid' },
      { name: 'Damkina', article: 'Damkina' },
      { name: 'Marduk', article: 'Marduk', parents: ['Enki', 'Damkina'] },
      { name: 'Nabu', article: 'Nabu', parents: ['Marduk'] },
    ],
  },
  {
    id: 'hindu',
    name: 'Hindu',
    article: 'Hindu deities',
    color: '#e9a25c',
    deities: [
      { name: 'Vishnu', article: 'Vishnu' },
      { name: 'Lakshmi', article: 'Lakshmi' },
      { name: 'Brahma', article: 'Brahma', parents: ['Vishnu'] },
      { name: 'Saraswati', article: 'Saraswati' },
      { name: 'Shiva', article: 'Shiva' },
      { name: 'Daksha', article: 'Daksha', parents: ['Brahma'] },
      { name: 'Marichi', article: 'Marichi', parents: ['Brahma'] },
      { name: 'Narada', article: 'Narada', parents: ['Brahma'] },
      { name: 'Kashyapa', article: 'Kashyapa', parents: ['Marichi'] },
      { name: 'Aditi', article: 'Aditi', parents: ['Daksha'] },
      { name: 'Diti', article: 'Diti', parents: ['Daksha'] },
      { name: 'Sati', article: 'Sati (Hindu goddess)', parents: ['Daksha'] },
      { name: 'Indra', article: 'Indra', parents: ['Kashyapa', 'Aditi'] },
      { name: 'Surya', article: 'Surya', parents: ['Kashyapa', 'Aditi'] },
      { name: 'Varuna', article: 'Varuna', parents: ['Kashyapa', 'Aditi'] },
      { name: 'Yama', article: 'Yama', parents: ['Surya'] },
      { name: 'Shani', article: 'Shani', parents: ['Surya'] },
      { name: 'Himavan', article: 'Himavat' },
      { name: 'Parvati', article: 'Parvati', parents: ['Himavan'] },
      { name: 'Ganga', article: 'Ganga (goddess)', parents: ['Himavan'] },
      { name: 'Ganesha', article: 'Ganesha', parents: ['Shiva', 'Parvati'] },
      { name: 'Kartikeya', article: 'Kartikeya', parents: ['Shiva', 'Parvati'] },
    ],
  },
  {
    id: 'shinto',
    name: 'Shinto',
    article: 'Japanese mythology',
    color: '#e6b4b4',
    deities: [
      { name: 'Izanagi', article: 'Izanagi' },
      { name: 'Izanami', article: 'Izanami' },
      { name: 'Kagutsuchi', article: 'Kagu-tsuchi', parents: ['Izanagi', 'Izanami'] },
      { name: 'Ebisu', article: 'Ebisu (mythology)', parents: ['Izanagi', 'Izanami'] },
      { name: 'Amaterasu', article: 'Amaterasu', parents: ['Izanagi'] },
      { name: 'Tsukuyomi', article: 'Tsukuyomi-no-Mikoto', parents: ['Izanagi'] },
      { name: 'Susanoo', article: 'Susanoo-no-Mikoto', parents: ['Izanagi'] },
      { name: 'Ame-no-Oshihomimi', article: 'Ame-no-oshihomimi', parents: ['Amaterasu'] },
      { name: 'Ninigi', article: 'Ninigi-no-Mikoto', parents: ['Ame-no-Oshihomimi'] },
      { name: 'Konohanasakuya-hime', article: 'Konohanasakuya-hime' },
      { name: 'Hoori', article: 'Hoori', parents: ['Ninigi', 'Konohanasakuya-hime'] },
      { name: 'Ryūjin', article: 'Ryūjin' },
      { name: 'Toyotama-hime', article: 'Toyotama-hime', parents: ['Ryūjin'] },
      { name: 'Ugayafukiaezu', article: 'Ugayafukiaezu', parents: ['Hoori', 'Toyotama-hime'] },
      { name: 'Jimmu', article: 'Emperor Jimmu', parents: ['Ugayafukiaezu'] },
      { name: 'Ōkuninushi', article: 'Ōkuninushi' },
      { name: 'Inari', article: 'Inari Ōkami' },
      { name: 'Sarutahiko', article: 'Sarutahiko Ōkami' },
      { name: 'Ame-no-Uzume', article: 'Ame-no-Uzume' },
      { name: 'Hachiman', article: 'Hachiman' },
    ],
  },
  {
    id: 'aztec',
    name: 'Aztec',
    article: 'Aztec mythology',
    color: '#8fc9a0',
    deities: [
      { name: 'Ōmeteōtl', article: 'Ōmeteōtl' },
      { name: 'Tezcatlipoca', article: 'Tezcatlipoca', parents: ['Ōmeteōtl'] },
      { name: 'Quetzalcoatl', article: 'Quetzalcoatl', parents: ['Ōmeteōtl'] },
      { name: 'Xipe Totec', article: 'Xipe Totec', parents: ['Ōmeteōtl'] },
      { name: 'Coatlicue', article: 'Coatlicue' },
      { name: 'Huitzilopochtli', article: 'Huitzilopochtli', parents: ['Coatlicue'] },
      { name: 'Coyolxauhqui', article: 'Coyolxauhqui', parents: ['Coatlicue'] },
      { name: 'Tlaloc', article: 'Tlaloc' },
      { name: 'Chalchiuhtlicue', article: 'Chalchiuhtlicue' },
      { name: 'Tonatiuh', article: 'Tonatiuh' },
      { name: 'Mictlantecuhtli', article: 'Mictlantecuhtli' },
      { name: 'Mictecacihuatl', article: 'Mictecacihuatl' },
      { name: 'Xochiquetzal', article: 'Xochiquetzal' },
      { name: 'Xochipilli', article: 'Xochipilli' },
      { name: 'Xolotl', article: 'Xolotl', parents: ['Ōmeteōtl'] },
      { name: 'Ehecatl', article: 'Ehecatl' },
      { name: 'Tlazolteotl', article: 'Tlazolteotl' },
      { name: 'Centeotl', article: 'Centeotl', parents: ['Tlazolteotl'] },
      { name: 'Mayahuel', article: 'Mayahuel' },
      { name: 'Itzpapalotl', article: 'Itzpapalotl' },
      { name: 'Mixcoatl', article: 'Mixcoatl' },
    ],
  },
  {
    id: 'celtic',
    name: 'Celtic',
    article: 'Irish mythology',
    color: '#9ec27a',
    deities: [
      { name: 'Danu', article: 'Danu (Irish goddess)' },
      { name: 'The Dagda', article: 'The Dagda' },
      { name: 'Boann', article: 'Boann' },
      { name: 'Aengus', article: 'Aengus', parents: ['The Dagda', 'Boann'] },
      { name: 'Brigid', article: 'Brigid', parents: ['The Dagda'] },
      { name: 'Bodb Derg', article: 'Bodb Derg', parents: ['The Dagda'] },
      { name: 'Nuada', article: 'Nuada Airgetlám' },
      { name: 'Dian Cécht', article: 'Dian Cecht' },
      { name: 'Cian', article: 'Cian', parents: ['Dian Cécht'] },
      { name: 'Miach', article: 'Miach', parents: ['Dian Cécht'] },
      { name: 'Airmed', article: 'Airmed', parents: ['Dian Cécht'] },
      { name: 'Balor', article: 'Balor' },
      { name: 'Ethniu', article: 'Ethniu', parents: ['Balor'] },
      { name: 'Lugh', article: 'Lugh', parents: ['Cian', 'Ethniu'] },
      { name: 'Lir', article: 'Lir' },
      { name: 'Manannán', article: 'Manannán mac Lir', parents: ['Lir'] },
      { name: 'The Morrígan', article: 'The Morrígan' },
      { name: 'Ogma', article: 'Ogma' },
      { name: 'Goibniu', article: 'Goibniu' },
      { name: 'Elatha', article: 'Elatha' },
      { name: 'Ériu', article: 'Ériu' },
      { name: 'Bres', article: 'Bres', parents: ['Elatha', 'Ériu'] },
      { name: 'Macha', article: 'Macha' },
      { name: 'Donn', article: 'Donn' },
    ],
  },
  {
    id: 'roman',
    name: 'Roman',
    article: 'Roman mythology',
    color: '#d9a066',
    /*
      Not the Greek line with the names swapped, though the sky and the
      harvest are shared: Rome's own figures are here — Janus, who has no
      parents anywhere; Romulus, son of Mars and a Vestal; Faunus, grandson
      of Saturn through Picus — and the borrowed ones keep Roman parentage,
      following Ovid's Fasti and Metamorphoses.
    */
    deities: [
      { name: 'Caelus', article: 'Caelus' },
      { name: 'Terra', article: 'Terra (mythology)' },
      { name: 'Saturn', article: 'Saturn (mythology)', parents: ['Caelus', 'Terra'] },
      { name: 'Ops', article: 'Ops', parents: ['Caelus', 'Terra'] },
      { name: 'Venus', article: 'Venus (mythology)', parents: ['Caelus'] },
      { name: 'Jupiter', article: 'Jupiter (mythology)', parents: ['Saturn', 'Ops'] },
      { name: 'Juno', article: 'Juno (mythology)', parents: ['Saturn', 'Ops'] },
      { name: 'Neptune', article: 'Neptune (mythology)', parents: ['Saturn', 'Ops'] },
      { name: 'Pluto', article: 'Pluto (mythology)', parents: ['Saturn', 'Ops'] },
      { name: 'Ceres', article: 'Ceres (mythology)', parents: ['Saturn', 'Ops'] },
      { name: 'Vesta', article: 'Vesta (mythology)', parents: ['Saturn', 'Ops'] },
      { name: 'Picus', article: 'Picus', parents: ['Saturn'] },
      { name: 'Mars', article: 'Mars (mythology)', parents: ['Jupiter', 'Juno'] },
      { name: 'Vulcan', article: 'Vulcan (mythology)', parents: ['Jupiter', 'Juno'] },
      { name: 'Minerva', article: 'Minerva', parents: ['Jupiter'] },
      { name: 'Apollo', article: 'Apollo', parents: ['Jupiter'] },
      { name: 'Diana', article: 'Diana (mythology)', parents: ['Jupiter'] },
      { name: 'Mercury', article: 'Mercury (mythology)', parents: ['Jupiter'] },
      { name: 'Proserpina', article: 'Proserpina', parents: ['Jupiter', 'Ceres'] },
      { name: 'Cupid', article: 'Cupid', parents: ['Venus', 'Mars'] },
      { name: 'Faunus', article: 'Faunus', parents: ['Picus'] },
      { name: 'Rhea Silvia', article: 'Rhea Silvia' },
      { name: 'Romulus', article: 'Romulus', parents: ['Mars', 'Rhea Silvia'] },
      { name: 'Quirinus', article: 'Quirinus' },
      { name: 'Janus', article: 'Janus' },
      { name: 'Fortuna', article: 'Fortuna' },
      { name: 'Bellona', article: 'Bellona (goddess)' },
      { name: 'Flora', article: 'Flora (mythology)' },
      { name: 'Liber', article: 'Liber' },
    ],
  },
  {
    id: 'chinese',
    name: 'Chinese',
    article: 'Chinese mythology',
    color: '#e8907c',
    /*
      Less a family than a court. The creators and the culture heroes mostly
      stand alone — Pangu, Nüwa, Fuxi, Shennong — and the lines of descent
      that do exist run through the legendary emperors, so most of these are
      members of the pantheon apart from any tree, which is honest to the
      material.
    */
    deities: [
      { name: 'Pangu', article: 'Pangu' },
      { name: 'Nüwa', article: 'Nüwa' },
      { name: 'Fuxi', article: 'Fuxi' },
      { name: 'Shennong', article: 'Shennong' },
      { name: 'Huangdi', article: 'Yellow Emperor' },
      { name: 'Leizu', article: 'Leizu' },
      { name: 'Shaohao', article: 'Shaohao', parents: ['Huangdi'] },
      { name: 'Zhuanxu', article: 'Zhuanxu' },
      { name: 'Emperor Ku', article: 'Emperor Ku' },
      { name: 'Yao', article: 'Emperor Yao', parents: ['Emperor Ku'] },
      { name: 'Shun', article: 'Emperor Shun' },
      { name: 'Yu the Great', article: 'Yu the Great' },
      { name: 'Jade Emperor', article: 'Jade Emperor' },
      { name: 'Xiwangmu', article: 'Queen Mother of the West' },
      { name: 'Di Jun', article: 'Di Jun' },
      { name: 'Xihe', article: 'Xihe (deity)' },
      { name: "Chang'e", article: "Chang'e" },
      { name: 'Hou Yi', article: 'Hou Yi' },
      { name: 'Chiyou', article: 'Chiyou' },
      { name: 'Gonggong', article: 'Gonggong' },
      { name: 'Zhurong', article: 'Zhurong' },
      { name: 'Nezha', article: 'Nezha' },
      { name: 'Sun Wukong', article: 'Sun Wukong' },
      { name: 'Guanyin', article: 'Guanyin' },
      { name: 'Erlang Shen', article: 'Erlang Shen' },
      { name: 'Mazu', article: 'Mazu' },
      { name: 'Zhong Kui', article: 'Zhong Kui' },
      { name: 'Cangjie', article: 'Cangjie' },
    ],
  },
  {
    id: 'maori',
    name: 'Māori',
    article: 'Māori mythology',
    color: '#8ab8c6',
    /* The children of Rangi and Papa, as the tribes of the North Island tell it. */
    deities: [
      { name: 'Ranginui', article: 'Ranginui' },
      { name: 'Papatūānuku', article: 'Papatūānuku' },
      { name: 'Tāne', article: 'Tāne', parents: ['Ranginui', 'Papatūānuku'] },
      { name: 'Tangaroa', article: 'Tangaroa', parents: ['Ranginui', 'Papatūānuku'] },
      { name: 'Tāwhirimātea', article: 'Tāwhirimātea', parents: ['Ranginui', 'Papatūānuku'] },
      { name: 'Tūmatauenga', article: 'Tūmatauenga', parents: ['Ranginui', 'Papatūānuku'] },
      { name: 'Rongo', article: 'Rongo', parents: ['Ranginui', 'Papatūānuku'] },
      { name: 'Haumia-tiketike', article: 'Haumia-tiketike', parents: ['Ranginui', 'Papatūānuku'] },
      { name: 'Rūaumoko', article: 'Rūaumoko', parents: ['Ranginui', 'Papatūānuku'] },
      { name: 'Whiro', article: 'Whiro', parents: ['Ranginui', 'Papatūānuku'] },
      { name: 'Hine-nui-te-pō', article: 'Hine-nui-te-pō', parents: ['Tāne'] },
      { name: 'Punga', article: 'Punga (mythology)', parents: ['Tangaroa'] },
      { name: 'Tinirau', article: 'Tinirau', parents: ['Tangaroa'] },
      { name: 'Māui', article: 'Māui (Māori mythology)' },
      { name: 'Hina', article: 'Hina (goddess)' },
      { name: 'Tāwhaki', article: 'Tāwhaki' },
      { name: 'Uenuku', article: 'Uenuku' },
      { name: 'Mahuika', article: 'Mahuika' },
    ],
  },
  {
    id: 'inca',
    name: 'Inca',
    article: 'Inca mythology',
    color: '#e6c05a',
    /* Viracocha's line, and the first Inca as children of the Sun. */
    deities: [
      { name: 'Viracocha', article: 'Viracocha' },
      { name: 'Inti', article: 'Inti', parents: ['Viracocha'] },
      { name: 'Mama Killa', article: 'Mama Killa', parents: ['Viracocha'] },
      { name: 'Pachamama', article: 'Pachamama' },
      { name: 'Mama Qucha', article: 'Mama Qucha' },
      { name: 'Manco Cápac', article: 'Manco Cápac', parents: ['Inti', 'Mama Killa'] },
      { name: 'Mama Ocllo', article: 'Mama Ocllo', parents: ['Inti', 'Mama Killa'] },
      { name: 'Supay', article: 'Supay' },
      { name: 'Urcuchillay', article: 'Urcuchillay' },
      { name: 'Ekeko', article: 'Ekeko' },
    ],
  },
  {
    id: 'slavic',
    name: 'Slavic',
    article: 'Slavic paganism',
    color: '#b8c7a0',
    /*
      The Slavs wrote nothing of their gods down, so the tree here is the
      reconstruction of Ivanov and Toporov, with Katičić's reading of the
      spring songs for Jarilo and Morana as the children of Perun and Mokosh.
      The names are attested; the lines between them are scholarship.
    */
    deities: [
      { name: 'Rod', article: 'Rod (Slavic religion)' },
      { name: 'Svarog', article: 'Svarog' },
      { name: 'Dazhbog', article: 'Dazhbog', parents: ['Svarog'] },
      { name: 'Svarozhits', article: 'Svarozhits', parents: ['Svarog'] },
      { name: 'Zorya', article: 'Zorya', parents: ['Dazhbog'] },
      { name: 'Perun', article: 'Perun' },
      { name: 'Mokosh', article: 'Mokosh' },
      { name: 'Jarilo', article: 'Jarilo', parents: ['Perun', 'Mokosh'] },
      { name: 'Morana', article: 'Marzanna', parents: ['Perun', 'Mokosh'] },
      { name: 'Veles', article: 'Veles (god)' },
      { name: 'Stribog', article: 'Stribog' },
      { name: 'Khors', article: 'Khors' },
      { name: 'Simargl', article: 'Simargl' },
      { name: 'Chernobog', article: 'Chernobog' },
      { name: 'Belobog', article: 'Belobog' },
      { name: 'Svetovit', article: 'Svetovit' },
      { name: 'Triglav', article: 'Triglav (mythology)' },
      { name: 'Radegast', article: 'Radegast (god)' },
      { name: 'Lada', article: 'Lada (mythology)' },
    ],
  },
  {
    id: 'persian',
    name: 'Persian',
    article: 'Persian mythology',
    color: '#c9b6ff',
    /*
      Zoroastrian, with the Zurvanite top: Time as the father of the Wise Lord
      and the Destructive Spirit, as the Sasanian heresy told it — the one
      account in which Ahura Mazda has a parent. Below him the Amesha Spentas,
      whom the Gathas call his own children.
    */
    deities: [
      { name: 'Zurvan', article: 'Zurvan' },
      { name: 'Ahura Mazda', article: 'Ahura Mazda', parents: ['Zurvan'] },
      { name: 'Angra Mainyu', article: 'Ahriman', parents: ['Zurvan'] },
      { name: 'Vohu Manah', article: 'Vohu Manah', parents: ['Ahura Mazda'] },
      { name: 'Asha', article: 'Asha', parents: ['Ahura Mazda'] },
      { name: 'Khshathra', article: 'Khshathra Vairya', parents: ['Ahura Mazda'] },
      { name: 'Armaiti', article: 'Armaiti', parents: ['Ahura Mazda'] },
      { name: 'Haurvatat', article: 'Haurvatat', parents: ['Ahura Mazda'] },
      { name: 'Ameretat', article: 'Ameretat', parents: ['Ahura Mazda'] },
      { name: 'Mithra', article: 'Mithra' },
      { name: 'Anahita', article: 'Anahita' },
      { name: 'Verethragna', article: 'Verethragna' },
      { name: 'Tishtrya', article: 'Tishtrya' },
      { name: 'Atar', article: 'Atar' },
      { name: 'Sraosha', article: 'Sraosha' },
      { name: 'Rashnu', article: 'Rashnu' },
      { name: 'Vayu-Vata', article: 'Vayu-Vata' },
      { name: 'Zam', article: 'Zam' },
      { name: 'Daena', article: 'Daena' },
    ],
  },
]
