/**
 * The Ideology Isles: eight mythologies, each with the family tree of its gods.
 *
 * A deity names its parents by name, within the same pantheon. From that the
 * tree lays itself out: a figure's generation is one below its parents', and a
 * figure with no parents but with children — a consort who marries into the
 * line — is placed level with its partner rather than up with the primordials.
 * Roots with neither parents nor children (Tlaloc, Thoth) are shown as
 * members of the pantheon standing apart, which is what they are.
 *
 * Every line here follows one named source tradition rather than a blend:
 * Hesiod for the Greeks, the Prose Edda for the Norse, the Heliopolitan Ennead
 * for Egypt, the Enūma Eliš for Babylon, the Kojiki for Japan, the Puranas for
 * India. Where traditions genuinely conflict — Huitzilopochtli has two
 * accounts of his birth — one is chosen and the other is not drawn, because a
 * family tree with two mothers for one god is not a tree. The Wikipedia
 * article each figure links to carries the full picture.
 */
export type Deity = { name: string; article: string; parents?: readonly string[] }

export type Pantheon = {
  id: string
  name: string
  article: string
  /** The islet's colour, and the tint of its orbs. */
  color: string
  deities: readonly Deity[]
}

export const PANTHEONS: readonly Pantheon[] = [
  {
    id: 'greek',
    name: 'Greek',
    article: 'Greek mythology',
    color: '#e8d8a6',
    deities: [
      { name: 'Chaos', article: 'Chaos (cosmogony)' },
      { name: 'Gaia', article: 'Gaia' },
      { name: 'Tartarus', article: 'Tartarus' },
      { name: 'Eros', article: 'Eros' },
      { name: 'Nyx', article: 'Nyx', parents: ['Chaos'] },
      { name: 'Erebus', article: 'Erebus', parents: ['Chaos'] },
      { name: 'Uranus', article: 'Uranus (mythology)', parents: ['Gaia'] },
      { name: 'Cronus', article: 'Cronus', parents: ['Gaia', 'Uranus'] },
      { name: 'Rhea', article: 'Rhea (mythology)', parents: ['Gaia', 'Uranus'] },
      { name: 'Oceanus', article: 'Oceanus', parents: ['Gaia', 'Uranus'] },
      { name: 'Hyperion', article: 'Hyperion (Titan)', parents: ['Gaia', 'Uranus'] },
      { name: 'Themis', article: 'Themis', parents: ['Gaia', 'Uranus'] },
      { name: 'Aphrodite', article: 'Aphrodite', parents: ['Uranus'] },
      { name: 'Helios', article: 'Helios', parents: ['Hyperion'] },
      { name: 'Selene', article: 'Selene', parents: ['Hyperion'] },
      { name: 'Zeus', article: 'Zeus', parents: ['Cronus', 'Rhea'] },
      { name: 'Hera', article: 'Hera', parents: ['Cronus', 'Rhea'] },
      { name: 'Poseidon', article: 'Poseidon', parents: ['Cronus', 'Rhea'] },
      { name: 'Hades', article: 'Hades', parents: ['Cronus', 'Rhea'] },
      { name: 'Demeter', article: 'Demeter', parents: ['Cronus', 'Rhea'] },
      { name: 'Hestia', article: 'Hestia', parents: ['Cronus', 'Rhea'] },
      { name: 'Leto', article: 'Leto' },
      { name: 'Metis', article: 'Metis (mythology)' },
      { name: 'Maia', article: 'Maia' },
      { name: 'Semele', article: 'Semele' },
      { name: 'Ares', article: 'Ares', parents: ['Zeus', 'Hera'] },
      { name: 'Hephaestus', article: 'Hephaestus', parents: ['Zeus', 'Hera'] },
      { name: 'Hebe', article: 'Hebe (mythology)', parents: ['Zeus', 'Hera'] },
      { name: 'Apollo', article: 'Apollo', parents: ['Zeus', 'Leto'] },
      { name: 'Artemis', article: 'Artemis', parents: ['Zeus', 'Leto'] },
      { name: 'Athena', article: 'Athena', parents: ['Zeus', 'Metis'] },
      { name: 'Hermes', article: 'Hermes', parents: ['Zeus', 'Maia'] },
      { name: 'Dionysus', article: 'Dionysus', parents: ['Zeus', 'Semele'] },
      { name: 'Persephone', article: 'Persephone', parents: ['Zeus', 'Demeter'] },
    ],
  },
  {
    id: 'norse',
    name: 'Norse',
    article: 'Norse mythology',
    color: '#b9c7d6',
    deities: [
      { name: 'Ymir', article: 'Ymir' },
      { name: 'Búri', article: 'Búri' },
      { name: 'Borr', article: 'Borr', parents: ['Búri'] },
      { name: 'Bestla', article: 'Bestla' },
      { name: 'Odin', article: 'Odin', parents: ['Borr', 'Bestla'] },
      { name: 'Vili', article: 'Vili and Vé', parents: ['Borr', 'Bestla'] },
      { name: 'Vé', article: 'Vili and Vé', parents: ['Borr', 'Bestla'] },
      { name: 'Frigg', article: 'Frigg' },
      { name: 'Jörð', article: 'Jörð' },
      { name: 'Thor', article: 'Thor', parents: ['Odin', 'Jörð'] },
      { name: 'Baldr', article: 'Baldr', parents: ['Odin', 'Frigg'] },
      { name: 'Höðr', article: 'Höðr', parents: ['Odin', 'Frigg'] },
      { name: 'Víðarr', article: 'Víðarr', parents: ['Odin'] },
      { name: 'Váli', article: 'Váli', parents: ['Odin'] },
      { name: 'Bragi', article: 'Bragi', parents: ['Odin'] },
      { name: 'Týr', article: 'Týr', parents: ['Odin'] },
      { name: 'Sif', article: 'Sif' },
      { name: 'Þrúðr', article: 'Þrúðr', parents: ['Thor', 'Sif'] },
      { name: 'Magni', article: 'Magni and Móði', parents: ['Thor'] },
      { name: 'Móði', article: 'Magni and Móði', parents: ['Thor'] },
      { name: 'Nanna', article: 'Nanna (Norse deity)' },
      { name: 'Forseti', article: 'Forseti', parents: ['Baldr', 'Nanna'] },
      { name: 'Njörðr', article: 'Njörðr' },
      { name: 'Freyr', article: 'Freyr', parents: ['Njörðr'] },
      { name: 'Freyja', article: 'Freyja', parents: ['Njörðr'] },
      { name: 'Heimdallr', article: 'Heimdallr' },
      { name: 'Loki', article: 'Loki' },
      { name: 'Angrboða', article: 'Angrboða' },
      { name: 'Hel', article: 'Hel (being)', parents: ['Loki', 'Angrboða'] },
      { name: 'Fenrir', article: 'Fenrir', parents: ['Loki', 'Angrboða'] },
      { name: 'Jörmungandr', article: 'Jörmungandr', parents: ['Loki', 'Angrboða'] },
      { name: 'Sleipnir', article: 'Sleipnir', parents: ['Loki'] },
    ],
  },
  {
    id: 'egyptian',
    name: 'Egyptian',
    article: 'Ancient Egyptian deities',
    color: '#d8b46a',
    deities: [
      { name: 'Nun', article: 'Nu (mythology)' },
      { name: 'Atum', article: 'Atum', parents: ['Nun'] },
      { name: 'Ra', article: 'Ra' },
      { name: 'Shu', article: 'Shu (Egyptian god)', parents: ['Atum'] },
      { name: 'Tefnut', article: 'Tefnut', parents: ['Atum'] },
      { name: 'Geb', article: 'Geb', parents: ['Shu', 'Tefnut'] },
      { name: 'Nut', article: 'Nut (goddess)', parents: ['Shu', 'Tefnut'] },
      { name: 'Osiris', article: 'Osiris', parents: ['Geb', 'Nut'] },
      { name: 'Isis', article: 'Isis', parents: ['Geb', 'Nut'] },
      { name: 'Set', article: 'Set (deity)', parents: ['Geb', 'Nut'] },
      { name: 'Nephthys', article: 'Nephthys', parents: ['Geb', 'Nut'] },
      { name: 'Horus', article: 'Horus', parents: ['Osiris', 'Isis'] },
      { name: 'Anubis', article: 'Anubis', parents: ['Set', 'Nephthys'] },
      { name: 'Hathor', article: 'Hathor', parents: ['Ra'] },
      { name: 'Bastet', article: 'Bastet', parents: ['Ra'] },
      { name: 'Sekhmet', article: 'Sekhmet', parents: ['Ra'] },
      { name: 'Maat', article: 'Maat', parents: ['Ra'] },
      { name: 'Thoth', article: 'Thoth' },
      { name: 'Ptah', article: 'Ptah' },
      { name: 'Amun', article: 'Amun' },
      { name: 'Mut', article: 'Mut' },
      { name: 'Khonsu', article: 'Khonsu', parents: ['Amun', 'Mut'] },
    ],
  },
  {
    id: 'mesopotamian',
    name: 'Mesopotamian',
    article: 'Ancient Mesopotamian religion',
    color: '#c6a27a',
    deities: [
      { name: 'Apsu', article: 'Abzu' },
      { name: 'Tiamat', article: 'Tiamat' },
      { name: 'Lahmu', article: 'Lahmu', parents: ['Apsu', 'Tiamat'] },
      { name: 'Lahamu', article: 'Lahamu', parents: ['Apsu', 'Tiamat'] },
      { name: 'Anshar', article: 'Anshar', parents: ['Lahmu', 'Lahamu'] },
      { name: 'Kishar', article: 'Kishar', parents: ['Lahmu', 'Lahamu'] },
      { name: 'Anu', article: 'Anu', parents: ['Anshar', 'Kishar'] },
      { name: 'Ki', article: 'Ki (goddess)' },
      { name: 'Enlil', article: 'Enlil', parents: ['Anu', 'Ki'] },
      { name: 'Enki', article: 'Enki', parents: ['Anu'] },
      { name: 'Ninlil', article: 'Ninlil' },
      { name: 'Nanna', article: 'Sin (mythology)', parents: ['Enlil', 'Ninlil'] },
      { name: 'Ninurta', article: 'Ninurta', parents: ['Enlil'] },
      { name: 'Nergal', article: 'Nergal', parents: ['Enlil', 'Ninlil'] },
      { name: 'Ningal', article: 'Ningal' },
      { name: 'Utu', article: 'Utu', parents: ['Nanna', 'Ningal'] },
      { name: 'Inanna', article: 'Inanna', parents: ['Nanna', 'Ningal'] },
      { name: 'Ereshkigal', article: 'Ereshkigal', parents: ['Nanna', 'Ningal'] },
      { name: 'Dumuzid', article: 'Dumuzid' },
      { name: 'Damkina', article: 'Damkina' },
      { name: 'Marduk', article: 'Marduk', parents: ['Enki', 'Damkina'] },
      { name: 'Nabu', article: 'Nabu', parents: ['Marduk'] },
    ],
  },
  {
    id: 'hindu',
    name: 'Hindu',
    article: 'Hindu deities',
    color: '#e9a25c',
    deities: [
      { name: 'Vishnu', article: 'Vishnu' },
      { name: 'Lakshmi', article: 'Lakshmi' },
      { name: 'Brahma', article: 'Brahma', parents: ['Vishnu'] },
      { name: 'Saraswati', article: 'Saraswati' },
      { name: 'Shiva', article: 'Shiva' },
      { name: 'Daksha', article: 'Daksha', parents: ['Brahma'] },
      { name: 'Marichi', article: 'Marichi', parents: ['Brahma'] },
      { name: 'Narada', article: 'Narada', parents: ['Brahma'] },
      { name: 'Kashyapa', article: 'Kashyapa', parents: ['Marichi'] },
      { name: 'Aditi', article: 'Aditi', parents: ['Daksha'] },
      { name: 'Diti', article: 'Diti', parents: ['Daksha'] },
      { name: 'Sati', article: 'Sati (Hindu goddess)', parents: ['Daksha'] },
      { name: 'Indra', article: 'Indra', parents: ['Kashyapa', 'Aditi'] },
      { name: 'Surya', article: 'Surya', parents: ['Kashyapa', 'Aditi'] },
      { name: 'Varuna', article: 'Varuna', parents: ['Kashyapa', 'Aditi'] },
      { name: 'Yama', article: 'Yama', parents: ['Surya'] },
      { name: 'Shani', article: 'Shani', parents: ['Surya'] },
      { name: 'Himavan', article: 'Himavat' },
      { name: 'Parvati', article: 'Parvati', parents: ['Himavan'] },
      { name: 'Ganga', article: 'Ganga (goddess)', parents: ['Himavan'] },
      { name: 'Ganesha', article: 'Ganesha', parents: ['Shiva', 'Parvati'] },
      { name: 'Kartikeya', article: 'Kartikeya', parents: ['Shiva', 'Parvati'] },
    ],
  },
  {
    id: 'shinto',
    name: 'Shinto',
    article: 'Japanese mythology',
    color: '#e6b4b4',
    deities: [
      { name: 'Izanagi', article: 'Izanagi' },
      { name: 'Izanami', article: 'Izanami' },
      { name: 'Kagutsuchi', article: 'Kagu-tsuchi', parents: ['Izanagi', 'Izanami'] },
      { name: 'Ebisu', article: 'Ebisu (mythology)', parents: ['Izanagi', 'Izanami'] },
      { name: 'Amaterasu', article: 'Amaterasu', parents: ['Izanagi'] },
      { name: 'Tsukuyomi', article: 'Tsukuyomi-no-Mikoto', parents: ['Izanagi'] },
      { name: 'Susanoo', article: 'Susanoo-no-Mikoto', parents: ['Izanagi'] },
      { name: 'Ame-no-Oshihomimi', article: 'Ame-no-oshihomimi', parents: ['Amaterasu'] },
      { name: 'Ninigi', article: 'Ninigi-no-Mikoto', parents: ['Ame-no-Oshihomimi'] },
      { name: 'Konohanasakuya-hime', article: 'Konohanasakuya-hime' },
      { name: 'Hoori', article: 'Hoori', parents: ['Ninigi', 'Konohanasakuya-hime'] },
      { name: 'Toyotama-hime', article: 'Toyotama-hime' },
      { name: 'Ugayafukiaezu', article: 'Ugayafukiaezu', parents: ['Hoori', 'Toyotama-hime'] },
      { name: 'Jimmu', article: 'Emperor Jimmu', parents: ['Ugayafukiaezu'] },
      { name: 'Ōkuninushi', article: 'Ōkuninushi' },
      { name: 'Inari', article: 'Inari Ōkami' },
    ],
  },
  {
    id: 'aztec',
    name: 'Aztec',
    article: 'Aztec mythology',
    color: '#8fc9a0',
    deities: [
      { name: 'Ōmeteōtl', article: 'Ōmeteōtl' },
      { name: 'Tezcatlipoca', article: 'Tezcatlipoca', parents: ['Ōmeteōtl'] },
      { name: 'Quetzalcoatl', article: 'Quetzalcoatl', parents: ['Ōmeteōtl'] },
      { name: 'Xipe Totec', article: 'Xipe Totec', parents: ['Ōmeteōtl'] },
      { name: 'Coatlicue', article: 'Coatlicue' },
      { name: 'Huitzilopochtli', article: 'Huitzilopochtli', parents: ['Coatlicue'] },
      { name: 'Coyolxauhqui', article: 'Coyolxauhqui', parents: ['Coatlicue'] },
      { name: 'Tlaloc', article: 'Tlaloc' },
      { name: 'Chalchiuhtlicue', article: 'Chalchiuhtlicue' },
      { name: 'Tonatiuh', article: 'Tonatiuh' },
      { name: 'Mictlantecuhtli', article: 'Mictlantecuhtli' },
      { name: 'Mictecacihuatl', article: 'Mictecacihuatl' },
      { name: 'Xochiquetzal', article: 'Xochiquetzal' },
    ],
  },
  {
    id: 'celtic',
    name: 'Celtic',
    article: 'Irish mythology',
    color: '#9ec27a',
    deities: [
      { name: 'Danu', article: 'Danu (Irish goddess)' },
      { name: 'The Dagda', article: 'The Dagda' },
      { name: 'Boann', article: 'Boann' },
      { name: 'Aengus', article: 'Aengus', parents: ['The Dagda', 'Boann'] },
      { name: 'Brigid', article: 'Brigid', parents: ['The Dagda'] },
      { name: 'Bodb Derg', article: 'Bodb Derg', parents: ['The Dagda'] },
      { name: 'Nuada', article: 'Nuada Airgetlám' },
      { name: 'Dian Cécht', article: 'Dian Cecht' },
      { name: 'Cian', article: 'Cian', parents: ['Dian Cécht'] },
      { name: 'Miach', article: 'Miach', parents: ['Dian Cécht'] },
      { name: 'Airmed', article: 'Airmed', parents: ['Dian Cécht'] },
      { name: 'Balor', article: 'Balor' },
      { name: 'Ethniu', article: 'Ethniu', parents: ['Balor'] },
      { name: 'Lugh', article: 'Lugh', parents: ['Cian', 'Ethniu'] },
      { name: 'Lir', article: 'Lir' },
      { name: 'Manannán', article: 'Manannán mac Lir', parents: ['Lir'] },
      { name: 'The Morrígan', article: 'The Morrígan' },
      { name: 'Ogma', article: 'Ogma' },
    ],
  },
]
